<?php
$_session = Mage::getSingleton('udropship/session')->getVendor()->getData();
//print_r("<pre>");
//print_r($_session);
//print_r("</pre>");
?>
<div class="generic-box">
<div class="batch-actions">
<h3 class="f-left">Contact Us</h3><br/>
</div>
<div id="contact-detail">
   <div id="contact-form">
      <div id="webform_3_success_text" class="std webforms-success-text" style="display:none"></div>
      <div id="webform_3_form">
         <h3>DROP US A MESSAGE</h3>
         <iframe id="webform_3_iframe" name="webform_3_iframe" style="width:0;height:0;border:0;position:absolute"></iframe>
         <form action="<?php echo Mage::getUrl(); ?>webforms/index/iframe/" method="post" name="webform_3" id="webform_3" enctype="application/x-www-form-urlencoded" class="webforms-VendorContactUs" target="webform_3_iframe">
            <input type="hidden" name="submitWebform_3" value="1"/>
            <input type="hidden" name="webform_id" value="3"/>
            <div class="fieldset fieldset-5">
            <table border="0" width="100%">
               <tr>
                  <td style="padding:5px;width: 150px;">Name</td>
                  <td style="padding:5px;">
                     <input type='text' name='field[17]' id='field[17]' class='input-text required-entry text-input' style='width: 100%' readonly="readonly" value="<?php echo $_session['vendor_name']; ?>"/>
                  </td>
               </tr>
               <tr>
                  <td style="padding:5px;">E-Mail</td>
                  <td style="padding:5px;">
                     <input type='text' name='field[18]' id='field[18]' class='input-text required-entry validate-email text-input' style='width: 100%' readonly="readonly" value="<? echo $_session['email']; ?>"/>
                  </td>
               </tr>
               <tr>
                  <td style="padding:5px;">Contact Number</td>
                  <td style="padding:5px;">
                     <input type='text' name='field[19]' id='field[19]' class='input-text required-entry text-input' style='width: 100%' readonly="readonly" value="<?php echo $_session['telephone']?$_session['telephone']:'NA'; ?>"/>
                  </td>
               </tr>
               <tr>
                  <td style="padding:5px;">Subject</td>
                  <td style="padding:5px;">
                     <input type='text' name='field[20]' id='field[20]' class='input-text required-entry text-input' style='width: 100%' value=""/>
                  </td>
               </tr>
               <tr>
                  <td style="padding:5px;">Message</td>
                  <td style="padding:5px;">
                     <textarea name='field[21]' id='field[21]' class='input-text required-entry' style='width: 100%'></textarea>
                  </td>
               </tr>
            </table>
            </div>
            <div class="buttons-set" style="position: relative; top: -70px; right: 48px; display: inline-block; float: right; border: 0;">
               <button type="button" class="button" id="webform_3_submit_button" onclick="webform_3_submit()" title="Send">
                  <span>
                     <span>Send</span>
                  </span>
               </button>
               <span class="please-wait" id="webform_3_sending_data" style="display:none;">
                 <img src="<?php echo Mage::getUrl('skin'); ?>frontend/default/default/images/opc-ajax-loader.gif" alt="Sending..." title="Sending..." class="v-middle" /><span id="webform_3_progress_text">Sending...</span>
               </span>
            </div>
         </form>
      </div>
   </div>
</div>
<br/>
</div>


<script type="text/javascript">
//<![CDATA[
var webform_3 = new VarienForm('webform_3', 0);
var webform_3_submit = function(){
	var form = webform_3;
	if(form.validator && form.validator.validate()){
		form.submit();
				$('webform_3_submit_button').hide();
		$('webform_3_sending_data').show();
			}
}

var iframe = $('webform_3_iframe');
iframe.observe('load',function(){
	var doc = this.contentDocument ? this.contentDocument: this.contentWindow.document;
	var json = {success:false};
	if(doc.body.innerHTML.unfilterJSON())
		json = doc.body.innerHTML.evalJSON();
	else return;
	if(json.success > 0){
		if(json.script){
			eval(json.script);
			return;
		}
		if(json.redirect_url){
			$('webform_3_progress_text').update('Redirecting');
			window.location = json.redirect_url;
			return;
		}
		$('webform_3_progress_text').update('Complete');
		Effect.Fade('webform_3_form',{
			duration: 0.5, from:1, to:0,
			afterFinish: function(){
				$('webform_3_success_text').update(json.success_text.unescapeHTML()).show();
				Effect.Fade('webform_3_success_text',{
					duration:0.5, from:0, to:1
				});
			}

		});
	} else {
		if($('webform_3_sending_data'))
			$('webform_3_sending_data').hide();
		if($('webform_3_submit_button'))
			$('webform_3_submit_button').show();
		if(json.errors && typeof(json.errors) == "string"){
			Dialog.alert(json.errors.unescapeHTML(),{
				title: "Error(s) occured",
				className: "magento",
				width:300,
				buttonClass: "button",
				okLabel: "Close",
				destroyOnClose: true,
				recenterAuto:true
			})
		} else {
			alert('Error(s) occured');
		}
		if(json.script){
			eval(json.script);
		}
	}
});
//]]>
</script>
