<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php $image_size = (int) Mage::getStoreConfig("featuredproducts/cmspage/max_image_dimension") ?>
<?php if (($_products = $this->getFeaturedProductCollection()) && $_products->getSize()): ?>
            <?php
            $i = 0;
            $row = 0;
            foreach ($_products->getItems() as $_product):
                ?>


                <div class="featured_product">
                    <div class="wrapper">
                        <!-- <a href="http://www.bugisstreet.com.sg/index.php/cachedlist/?cat=317"> -->
                        <a  href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                            <div class="imgwrap"> <img  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_size, $image_size) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" > </div>
                        </a>
                    </div>  <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>  <?php echo $this->getPriceHtml($_product, true) ?>
                </div>


    <?php endforeach; ?>





<?php endif; ?>