<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ui.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.bxslider.min.js') ?>"></script>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/jquery.fancybox.css') ?>">
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/validationEngine.jquery.css') ?>">
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/product.js') ?>"></script>

<script src="<?php echo $this->getSkinUrl('js/jquery.isotope.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.isotope.perfectmasonry.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.fancybox.pack.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.validationEngine-en.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.validationEngine.js') ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.bxslider.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.pajinate.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.panzoom.js') ?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/main.js') ?>"></script>


<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>

<div class="product-detail">
    <div class="detail-slider">
        <?php if (count($this->getGalleryImages()) > 1): ?>
            <div class="bxslider-prev"></div>
            <div class="bxslider-next"></div>
        <?php endif; ?>
        <ul class="bxslider-detail" style="overflow: hidden;height: 400px;">
            <?php if (count($this->getGalleryImages()) == 0): ?>
                <li class="slideitem">
                    <a class="open-fancy" href="#gallery" data-seq="thumb1">
                        <h2>+ Zoom</h2>
                    </a>

                    <div class="imgwrap">
                        <img style="width: auto;height: 400px;margin: 0 auto;" id="image-0"
                             class="gallery-image"
                             src="<?php echo $this->getskinUrl('images/logo_detail.gif') ?>"
                             data-zoom-image="<?php echo $this->getskinUrl('images/logo_detail.gif') ?>"/>
                    </div>
                </li>
            <?php else: ?>
                <?php $i = 0;
                foreach ($this->getGalleryImages() as $_image): ?>
                    <?php if ($this->isGalleryImageVisible($_image)): ?>
                        <li class="slideitem" style="width: 400px">
                            <a class="open-fancy" href="#gallery" data-seq="thumb<?php echo $i + 1 ?>">
                                <h2>+ Zoom</h2>
                            </a>

                            <div class="imgwrap">
                                <img style="width:auto;height: 400px;margin: 0 auto;" id="image-<?php echo $i; ?>"
                                     class="gallery-image"
                                src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(1000); ?>
                                "
                                data-zoom-image="<?php echo $this->getGalleryImageUrl($_image); ?>" />
                            </div>
                        </li>
                    <?php endif; ?>

                    <?php $i++; endforeach; ?>
            <?php endif; ?>
        </ul>
        <?php if (count($this->getGalleryImages()) > 1): ?>
            <div class="bxslider-pager"></div>
        <?php endif; ?>

    </div>
</div>
<div id="gallery" class="clearfix">
    <div class="galleryClose">
        <div class="wrapper"></div>
    </div>
    <div class="zGallery-controls">
        <div class="zg-left"></div>
        <div class="zg-right"></div>
    </div>
    <div class="fullImg"></div>
    <div class="thumbImg">
        <div class="thmimgwrapper"></div>
    </div>
</div><!--17 jan-->
<div class="showHideThumbs"></div>
<div class="thumbImg"></div>
<!--<script src="http://www.bugisstreet.com.sg/skin/frontend/default/bso/js/vendor,_jquery.pajinate.min.js+dist,_jquery.panzoom.js.pagespeed.jc.VEvdHGhnXY.js"></script><script>eval(mod_pagespeed_sJG5Hi0G_K);</script>-->
<!--<script>eval(mod_pagespeed_wAwvmNsJsV);</script>-->
<script type="text/javascript">//<![CDATA[
    function do_submit_to_cart(id, id2) {
        if (!attr_selected) {
            document.location = "#select_attr_area";
            jQuery('#select_attr_noob_msg').show();
            return;
        }
        var amt = parseInt(jQuery('#product_addtocart_form').find('input[name=qty' + id + ']').val());
        jQuery('.qty_error').hide();
        if (!(amt == NaN || amt < 1)) {
            jQuery('#product_addtocart_form').find('input[name=qty]').val(amt);
            udmpChangeSelectedVendor.defer('product_vendors_' + id2 + '_udropship_vendor', true);
        } else {
            jQuery('#qty_error_' + id + '_' + id2).show();
        }
    }
    jQuery(document).ready(function () {
        jQuery('#reviewtab-2').pajinate({
            items_per_page: 3,
            item_container_id: '.reviews-all',
            nav_label_first: '',
            nav_label_last: '',
            nav_label_prev: '',
            nav_label_next: '→'
        });
        if (!jQuery('#reviewtab-2 .reviews-all li').length) {
            jQuery('#reviewtab-2 .pagination a.next_link').hide();
        }
    });
    (function () {
        var $section = jQuery('#inverted-contain');
        $section.find('.panzoom').panzoom({
            $zoomIn: $section.find(".zoom-in"),
            $zoomOut: $section.find(".zoom-out"),
            $zoomRange: $section.find(".zoom-range"),
            $reset: $section.find(".reset"),
            startTransform: 'scale(1.1)',
            increment: 0.1,
            minScale: 1,
            contain: 'invert'
        }).panzoom('zoom');
    })();
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function (button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;
            if (url) {
                form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }
            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);
    productAddToCartForm.submitLight = function (button, url) {
        if (this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }
            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]></script>
<script>
    var image_list = "";
    var edited = false;
    function selectcolor(attrid, valid, slide_ids) {
        if (slide_ids.length > 0) {
            if (!edited) {
                // only grab non-clone "original" images
                image_list = jQuery('.slideitem:not(.bx-clone)');
                edited = true;
            }
            //remove all images
            /*jQuery('.slideitem').each(function() {
             jQuery(this).remove()
             });*/
            jQuery('.bxslider-detail').empty();
            if (product_slider) {
                product_slider.destroySlider();
            }

            //show only the ones in the slide_ids
            // we don't select the duplicates anymore so..
            // var images_count = image_list.length / 3;
            var i = 1;
            image_list.each(function () {
                if (slide_ids.indexOf(i - 1) > -1) {
                    jQuery('.bxslider-detail').append(this);
                }
                // the cloned copies are automatically created, no need to re-add
                i++;
            });

            // reload the damn slider to avoid funny paging problems
            product_slider = jQuery('.bxslider-detail').bxSlider({
                preloadImages: 'all',
                touchEnabled: true,
                minSlides: 1,
                maxSlides: 6,
                moveSlides: 1,
                slideWidth: 400,
                slideMargin: 0,
                useCSS: false,
                responsive: true,
                pagerSelector: jQuery('.bxslider-pager'),
                nextText: '',
                prevText: '',
                onSliderLoad: function () {
                    jQuery('.bxslider-detail .slideitem').hover(function () {
                        jQuery('.open-fancy').hide();
                        jQuery(this).children('.open-fancy').show();
                    }, function () {
                        jQuery(this).children('.open-fancy').hide();
                    });
                }
            });

            jQuery('.bxslider-detail .slideitem img').fadeIn();
            //product_slider.goToSlide(1);

            // refresh all the zoom-in popup stuff
            jQuery('.bxslider-detail li').hover(function () {
                jQuery('.open-fancy').hide();
                jQuery(this).children('.open-fancy').show();
            }, function () {
                jQuery(this).children('.open-fancy').hide();
            });
            // refresh the arrow logic shit
            if (jQuery('.content').hasClass('bso-product-detail') && jQuery('.detail-slider').length > 0) {
                tslideitems = jQuery('.bxslider-detail li').size();
                tcloneitems = jQuery('.bxslider-detail li.bx-clone').size();
                trealitems = tslideitems - tcloneitems;
                if (((trealitems) < 3) && (jQuery('.content').width() > (trealitems * 400))) {
                    jQuery('.bxslider-prev').hide();
                    jQuery('.bxslider-next').hide();
                } else if (jQuery('.content').width() < (trealitems * 400)) {
                    jQuery('.bxslider-prev').show();
                    jQuery('.bxslider-next').show();
                }
            }
            refresh_open_fancy();
        }
        if (jQuery('#attribute' + attrid).length <= 0) {
            jQuery('#select_attr_out_of_stock_msg').show();
            jQuery('#main_addtocart_button').addClass("inactivebutton");
        } else {
            if (jQuery('#sizeselectdiv')) {
                jQuery('#attribute' + attrid).val(valid);
                jQuery('attribute' + attrid).triggerEvent('change');
                var sizeid = 154;
                //console.log(jQuery('#attribute' + sizeid).find('option').length);
                if (jQuery('#attribute' + sizeid).find('option').length < 2) {
                    jQuery('#select_attr_color_out_of_stock_msg').show();
                    jQuery('#main_addtocart_button').addClass("inactivebutton");
                } else {
                    jQuery('#select_attr_color_out_of_stock_msg').hide();
                    jQuery('#main_addtocart_button').removeClass("inactivebutton");
                    jQuery('#sizeselectdiv').css('display', 'block');
                    jQuery('.size-box').hide();
                    jQuery('.size-box').removeClass('active');
                    // jQuery('.retailer.vendordiv').hide();
                    we_got_vendors = false;
                    //jQuery('#retailer-list').hide();
                    jQuery('#attribute' + sizeid).find('option').each(function (i, v) {
                        if (jQuery(v).val() != "") {
                            jQuery('#size-box-' + jQuery(v).val()).show();
                        }

                        if (jQuery('#attribute' + sizeid).find('option').length < 3) {
                            // < 3 because there's an empty one
                            jQuery('#size-box-' + jQuery(v).val()).trigger("click");
                        }
                    });
                }
            } else {
                attr_selected = true;
            }
        }
    }
</script>
