
<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
$path = $url->getPath();
$pathFragments = explode('/', $path);
$end = $pathFragments['5'];
$_code = 'mpperproductshipping5';
$_title = Mage::getStoreConfig("carriers/$_code/title");

if(Mage::getStoreConfig("carriers/$_code/active")==1){
$allowedshipping = json_decode(Mage::getSingleton('customer/session')->getCustomer()->getAllowedShipping(),true);
$shipcharges=Mage::getModel('catalog/product')->load($this->getRequest()->getParam('id'))->getMpShippingCharge5();
$customerObj  = Mage::getSingleton('customer/session')->getCustomer();

// edit
    $productowner = Mage::getModel('marketplace/product')->getCollection()
        ->addFieldToFilter('mageproductid', $this->getRequest()->getParam('id'))
        ->addFieldToFilter('userid', $customerObj->getId());
    foreach($productowner as $product){
        $list_shippings = explode( ',', $product->getAllowedShipping());
    }
?>
	<li class="shipping_custom">
        <?php if($end=="new"):?>
            <input  type="checkbox" name="shippingmethod[]" value="<?php echo $_code;?>" />
        <?php else: ?>
            <!--<input  type="checkbox" name="shippingmethod[]" <?php /*echo in_array($_code,$allowedshipping)? "checked='checked'":"";*/?> value="<?php /*echo $_code;*/?>" />-->
            <input  type="checkbox" name="shippingmethod[]" <?php echo in_array($_code,$list_shippings)? "checked='checked'":"";?> value="<?php echo $_code;?>" />
        <?php endif; ?>
	<label><?php echo $_title; ?>:</label>
	<div class="input-box">
		<input type="text" class="validate-zero-or-greater input-text custom_ship" value="<?php if($shipcharges){echo $shipcharges;}else{echo '0';}?>" name="mp_shipping_charge5" id="mp_shipping_charge5"/>
	</div>
</li>
<?php } ?>