<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$uri = $_SERVER['REQUEST_URI'];
$segment = explode("/", $uri);


$partner = Webkul_Marketplace_Block_Collection::getProfileDetail2();
$seller_url = trim($partner['profileurl']);

$sellers = Mage::getModel('marketplace/userprofile')->getCollection()
    ->addFieldToFilter('profileurl', $seller_url);
foreach($sellers as $seller){
    if($seller['bannerpic']!=''){
        $bannerpic = $seller['bannerpic'];
    }
    else {
        $bannerpic = "banner-image.png";
    }
    $bannerpic=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'avatar/'.$bannerpic;

}

if($seller_url != ""){
?>

<div style="height: 90px" id="demoretailer243" class="retailer premium vendordiv">
    <div class="r-name">
        <div style="float:left;padding-left:35px;">
            <a class="shop-title"
               style="color:#333; font-weight: bold; font-size: 1.3em;"
               href="<?php echo $this->getUrl('marketplace/seller/profile') . $seller_url ?>">
                <?php echo $partner['shoptitle'] ?>
            </a>
            <br>
            <a style="font-size:0.8em;padding:3px;border:1px solid;font-weight:normal; color: #333;margin-right: 5px"
               href="<?php echo rtrim($this->getUrl('seller_detail?seller=' . $seller_url), '/'); ?>">
                See All Products
            </a>
            <a style="font-size:0.8em;padding:3px;border:1px solid;font-weight:normal; color: #333"
               href="<?php echo $this->getUrl('marketplace/seller/profile') . $seller_url ?>">
                Shop Info
            </a>
        </div>
    </div>
</div>
<?php
}
if($seller_url != ""){
    ?>
    <div class="collection-banner"><img style="max-width: 99.4%;margin: 0 auto;" src="<?php echo $bannerpic; ?>" alt="no image"/></div>
<?php
}
?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery(".filter-over").css({
            opacity: 1,
            height: "auto"
        });
        var htmlFilter = jQuery(".block_filter").clone();
        jQuery(".filter-over").removeClass("toggled");
        jQuery(".block_filter").remove();
        jQuery(".control_filter").append(htmlFilter);
        jQuery(".col-main .block-layered-nav.one-filter-column .block-subtitle").click(function(){
            jQuery(".sort-over").removeClass("toggled");
        });
    });
</script>
<div class="control_filter abc">
    <div class="category-title page-title topnav-sub">
        <h2 class="product-title">
            <?php
            foreach ($segment as $params) {
                if ($params == 'new-arrivals-women' || $params == 'new-arrivals-men' || $params == 'new-arrivals-home-living' || $params == 'new-arrivals-electronics' ||$params == 'new-arrivals-gifts') {
                    echo 'New Arrivals';
                }
                if ($params == 'popular-women' || $params == 'popular-men' || $params == 'popular-home-living' || $params == 'popular-electronics' || $params == 'popular-gifts') {
                    echo 'Featured';
                }
            }
            ?>
        </h2>
    </div>
</div>
<?php
/* @var $this Mage_Core_Block_Template */

/* @var $_core Mana_Core_Helper_Data */
$_core = Mage::helper('mana_core');

/* @var $core Mana_Filters_Helper_Data */
$_filters = Mage::helper('mana_filters');

$_hideWhenNoFiltersApplied =
    ($this->hasData('hide_when_no_filters_applied')
        ? $this->getData('hide_when_no_filters_applied')
        : Mage::getStoreConfigFlag('mana_filters/display/hide_cms_product_list'));
$_isFilterApplied = ($state = $_filters->getLayer()->getState()) && $state->getFilters();
$_isProductListVisible = $_isFilterApplied || !$_hideWhenNoFiltersApplied;

?>
<?php if ($_isProductListVisible) : ?>
    <?php echo $this->getChildHtml('product_list') ?>
<?php else: ?>
    <?php echo $_core->getEmptyBlockHtml($this->getChild('product_list')) ?>
<?php endif; ?>
