<?php 
$partner=$this->getProfileDetail();
if($partner->getprofileurl()!=''){
?>
<style>
.main{background-image:none;background-color:<?php echo $partner->getbackgroundth();?>}
</style>
<?php
$_productCollection=$this->getCollection();
$_helper = $this->helper('catalog/output');
$helper=Mage::helper('marketplace');
$partner=$this->getProfileDetail();
$productname=$this->getRequest()->getParam('name');
$bannerpic=$partner->getbannerpic()!=''?$partner->getbannerpic():"banner-image.png";
$bannerpic=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'avatar/'.$bannerpic;
$today =date('Y-m-d');
?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ias.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/callbacks.js') ?>"></script>
    <script type="text/javascript">
        jQuery.ias({
            container: '.category-products',
            item: '.products-grid',
            pagination: '.toolbar .pager',
            next: 'div.pages a.next:first',
            loader: '<img src="<?php echo $this->getSkinUrl('images/preloader.gif'); ?>"  />'
        });
    </script>
<div class="collection-banner"><img src="<?php echo $bannerpic; ?>" alt="no image"/></div>
<div class="wk_mp_design" style="padding-top: 10px;">
    <div class="block block-account">   
        <div class="block-title">   
            <strong><span><h2 style="font-size: 20px; color: #333"><?php echo $helper->__("SELLER'S COLLECTION") ?></h2></span></strong>
        </div>
    </div>
    <div class="fieldset wk_mp_fieldset" <?php if($_productCollection->count()){ echo 'style="padding: 0;"';}?>>
        <?php if(!$_productCollection->count()): ?>
        <p class="note-msg" style="padding:5px;"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else: ?>

        <!-- Add Filter -->
            <ul class="productlisting-filters">
                <li class="filter-filters">
                    <a id="filter-trig"><span class="label">Filter</span></a>
                </li>
                <li class="filter-sort">
                    <a><span class="label">Sort</span></a>
                </li>
            </ul>
            <div class="border-bottom"></div>
            <div class="filter-over clearfix" id="filters">
                <div class="filter-mobile-heading">
                    <h3>Filter By</h3>

                    <div class="mobilefilter-close"></div>
                </div>
                <?php  //echo $this->getLayout()->createBlock('mana_filters/view')->setTemplate('manapro/filteradvanced/view.phtml')->toHtml(); ?>


            </div>
            <div class="sort-over">
                <ul>
                    <li onclick="dosort('created_at', 'desc');">New Arrivals</li>
                    <li onclick="dosort('price', 'desc');">Price (High to Low)</li>
                    <li onclick="dosort('price', 'asc');">Price (Low to High)</li>
                    <li onclick="dosort('name', 'asc');">Name (A-Z)</li>
                    <li onclick="dosort('most_viewed', 'desc');">Most Viewed</li>
                    <li onclick="dosort('bestsellers', 'desc');">Popular</li>
                </ul>
            </div>
        <!-- End add filter -->

        <div class="category-products">        	
            <?php if($productname!=''){ ?>
            <div class="page-title">
                <h1><?php echo $this->__('Search results for "').$productname.$this->__('"'); ?></h1>
            </div>
            <?php } ?>
            <?php echo $this->getToolbarHtml() ?>
            <?php // List mode ?>
            <?php if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
            <?php foreach ($_productCollection as $_product): ?>
        	    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                    <?php // Product Image ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <img src="<?php echo Mage::helper('catalog/image')->init($_product,'thumbnail')->resize(480); ?>"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <?php // Product description ?>
                    <div class="product-shop">
                        <div class="f-fix">
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                            <?php if($_product->getRatingSummary()): ?>
                            <?php echo Mage_Catalog_Block_Product::getReviewsSummaryHtml($_product) ?>
                            <?php endif; ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

            <?php else: ?>

            <?php // Grid Mode ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php if ($i++%$_columnCount==0): ?>
                <ul class="products-grid seller-grid" >
                <?php endif ?>
                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <img src="<?php echo Mage::helper('catalog/image')->init($_product,'thumbnail')->resize(480); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>

                        <div class="desc">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-description clearfix">
                                <div class="desc-left">
                        <span class="item-name">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </span>
                                </div>
                                <div class="desc-right">
                                <span class="item-price">
                                  <?php echo $this->getPriceHtml($_product, true) ?>
                                </span>
                                </div>
                            </a>
                        </div>
                    </li>
                <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                </ul>
                <?php endif ?>
                <?php endforeach ?>
                <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
            <?php endif; ?>

            <div class="toolbar-bottom">
                <?php echo $this->getToolbarHtml() ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
if (typeof jQuery == 'undefined'){
    document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script>
<script>	
jQuery.noConflict();
(function($wk_jq){
	$wk_jq('.toolbar select option').each(function(){
        $url=$wk_jq(this).attr('value').replace('collection/','collection/'+'<?php echo $partner->getprofileurl();?>/');
        $wk_jq(this).attr('value',$url);
    });
    $wk_jq('.toolbar a').each(function(){
        $wk_jq(this).attr('href',$wk_jq(this).attr('href').replace('collection/','collection/'+'<?php echo $partner->getprofileurl();?>/'));
    });
})(jQuery);

</script>
<?php } ?>

<script type="text/javascript">
    function updateQueryStringParameter(uri, key, value) {
        var re = new RegExp("([?|&])" + key + "=.*?(&|#|$)", "i");
        if (uri.match(re)) {
            return uri.replace(re, '$1' + key + "=" + value + '$2');
        } else {
            var hash = '';
            var separator = uri.indexOf('?') !== -1 ? "&" : "?";
            if (uri.indexOf('#') !== -1) {
                hash = uri.replace(/.*#/, '#');
                uri = uri.replace(/#.*/, '');
            }
            return uri + separator + key + "=" + value + hash;
        }
    }
    function removeQueryStringParameter(url, parameter) {
        var urlparts = url.split('?');
        if (urlparts.length >= 2) {
            var prefix = encodeURIComponent(parameter) + '=';
            var pars = urlparts[1].split(/[&;]/g);
            for (var i = pars.length; i-- > 0;) {
                if (pars[i].lastIndexOf(prefix, 0) !== -1) {
                    pars.splice(i, 1);
                }
            }
            url = urlparts[0] + '?' + pars.join('&');
            return url;
        } else {
            return url;
        }
    }
    function dosort(order, dir) {
        document.location = updateQueryStringParameter(updateQueryStringParameter(document.URL, 'order', order), 'dir', dir);
    }
    function load_filters() {
        var url = document.URL;
        var colorfilters = jQuery('.swatch-color.active').map(function () {
            return jQuery(this).data('value');
        }).get();
        if (colorfilters.length > 0) {
            url = updateQueryStringParameter(url, 'color', colorfilters.join(","));
        } else {
            url = removeQueryStringParameter(url, 'color');
        }
        var sizefilters = jQuery('.size-box.active').map(function () {
            return jQuery(this).data('value');
        }).get();
        if (sizefilters.length > 0) {
            url = updateQueryStringParameter(url, 'clothes_size', sizefilters.join(","));
        } else {
            url = removeQueryStringParameter(url, 'clothes_size');
        }
        var vendorfilters = jQuery('input[name=a-d]:checked').map(function () {
            return jQuery(this).val();
        }).get();
        if (vendorfilters.length > 0) {
            url = updateQueryStringParameter(url, 'vendorname', vendorfilters.join(","));
        } else {
            url = removeQueryStringParameter(url, 'vendorname');
        }
        url = updateQueryStringParameter(url, 'price', jQuery('.price-slider').slider('values').join(","));
        document.location = url;
    }</script>
