<?php
$wholedata=$this->getRequest()->getParams();
$configproducts = $this->getConfigurableProduct();
$ch = $configproducts->getName();

$helper=Mage::helper('marketplace');
$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
$allow_pro_type=Mage::getStoreConfig('marketplace/marketplace_options/allow_for_seller');

//if($isPartner==1 && strpos($allow_pro_type,'configurable') !== false){
if($isPartner==1){
    /*$customid=Mage::getSingleton('customer/session')->getCustomerId();
    $partner=Mage::getModel('marketplace/userprofile')->getPartnerProfileById($customid);
        $groups = Mage::getResourceModel('customer/group_collection')
            ->addFieldToFilter('customer_group_id', $partner['member'])
            ->load();
        foreach($groups as $group){
            $limit = $group['product_listing'];
        }
        $flag = 0;
        if($limit!=0){
            $collection = Mage::getModel('marketplace/product')->getCollection()
                ->addFieldToFilter("userid", $partner['sellerid']);
            $countproduct = count($collection);
            foreach($collection as $row){
                $_product = Mage::getModel('catalog/product')->load($row['mageproductid']);
                if($_product['type_id']=='configurable'){
                    $conf = Mage::getModel('catalog/product_type_configurable')->setProduct($_product);
                    $simple_collection = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();
                    $countproduct = $countproduct + count($simple_collection);
                }
            }
            if($limit <=  $countproduct){
                $flag = 1;
            }
        }*/
    ?>
<!--    <script type="text/javascript" src="--><?php //echo $this->getSkinUrl("js/jquery.easyPaginate.js") ?><!--"></script>-->
    <script type="text/javascript" src="<?php echo $this->getSkinUrl("js/jquery.quick.pagination.js") ?>"></script>
    <script type="text/javascript">
        /*jQuery(document).ready(function(){

            jQuery('.list_associates tbody').quickPager({pageSize:"12"});

        });*/
        if (typeof jQuery == 'undefined'){
            document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
        }

    </script>
    <style type="text/css">
        .wk_mp_list_table th,td{
            text-align: center;
        }
    </style>
    <form action="<?php echo $this->getUrl('marketplace/marketplaceaccount/quickcreate') ?>" method="post" id="form-quickcreate">
        <!--<input type="hidden" name="flag" id="flag" value="<?php /*echo $flag */?>" />-->
        <div class="page-title">
            <h1 style="float:left; "><?php echo $configproducts->getName(); ?></h1>

        </div>
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <div class="wk_mp_design">
            <div class="block block-account">
                <div class="block-title">
                    <strong><span><h4><?php echo $helper->__('Quick create') ?></h4></span></strong>
                </div>
            </div>
            <div class="fieldset wk_mp_fieldset">
                <input type="hidden" name="mainid" id="productid" value="<?php echo $wholedata['id']; ?>"/>
                <input type="hidden" name="attr" id="attr" value="<?php echo $wholedata['attr']; ?>" />
                <ul  class="form-list" id="wk_bodymain" style="margin-top: -70px">
                    <li>
                        <label class="required" style="display: none"><em>*</em><?php echo $helper->__('Name') ?>:</label>
                        <div class="input-box"><input type="hidden" name="Name" class="input-text" id="nameproduct"></div>
                    </li>
                    <li>
                        <label class="required" style="display: none"><em>*</em><?php echo $helper->__('Sku') ?>:</label>
                        <div class="input-box">
                            <input type="hidden" name="Sku" id="sku" class="input-text required-entry">
                            <div id="skuavail" >
                                <span class="success-msg skuavailable"><?php echo $helper->__('SKU Available') ?></span>
                            </div>
                            <div id="skunotavail" >
                                <span class="error-msg skunotavailable"><?php echo $helper->__('SKU Already Exist') ?></span>
                            </div>
                        </div>
                    </li>
                    <li>
                        <label ><?php //echo $helper->__('Weight') ?></label>
                        <div class="input-box"><input type="hidden" name="weight" class="input-text required-entry validate-digits" value="10"></div>
                    </li>
                    <li>
                        <label class="required"><em>*</em><?php echo $helper->__('Status') ?>:</label>
                        <div class="input-box">
                            <select id="simple_product_status" class="input-text required-entry" name="status">
                                <option value="1"><?php echo $helper->__('Enabled') ?></option>
                                <option value="2"><?php echo $helper->__('Disabled') ?></option>
                            </select>
                        </div>
                    </li>
                    <li>
                        <label class="required"><em>*</em><?php echo $helper->__('Visibility') ?>:</label>
                        <div class="input-box">
                            <select id="simple_product_visibility" class="input-text required-entry" name="visibility">
                                <option value="1"><?php echo $helper->__('Not Visible Individually') ?></option>
<!--                                <option value="2">--><?php //echo $helper->__('Catalog') ?><!--</option>-->
<!--                                <option value="3">--><?php //echo $helper->__('Search') ?><!--</option>-->
<!--                                <option value="4">--><?php //echo $helper->__('Catalog, Search') ?><!--</option>-->
                            </select>
                        </div>
                    </li>
                    <li>
                        <label class="required"><em>*</em><?php echo $helper->__('Qty') ?>:</label>
                        <div class="input-box"><input type="text" name="Qty" class="input-text required-entry validate-digits"/></div>
                    </li>
                    <?php
                    $configattr = Mage::getModel('catalog/product_type_configurable')->getConfigurableAttributesAsArray($configproducts);
                    foreach($configattr as $attribute) { ?>
                        <li>
                            <label class="required"><em>*</em><?php echo $attribute['frontend_label']; ?>:</label>
                            <div class="input-box supperattr">
                                <select class="input-text required-entry custattr" id="<?php echo $attribute['id']; ?>"  name="<?php echo $attribute['attribute_code'];?>">
                                    <?php
                                    $attributeOptions = $this->getAttributeOptions($attribute['attribute_code']);
                                    foreach($attributeOptions as $each){  ?>
                                        <option value="<?php echo $each["value"]; ?>" ><?php echo $each["label"]; ?></option>
                                    <?php } ?>
                                </select>
                                <!--<div style="display:none;">
                                    <label class="required"><?php /*echo $helper->__('Price') */?><b><?php /*$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); echo  " (". Mage::app()->getLocale()->currency( $currency_code )->getSymbol().")"; */?></b>:</label>
                                    <?php
/*                                    foreach($attributeOptions as $each){
                                        foreach ($attribute['values'] as $value) {
                                            if($each['value']==$value['value_index'] && $value['pricing_value']!=''){ */?>
                                            <span class="<?php /*echo $value['value_index'] */?>" style="display:none;" id="<?php /*echo $value['value_index'] */?>" type="text"><b>+<?php /*echo Mage::helper('core')->currency($value['pricing_value'], true, false); */?></b></span><?php
/*                                            }
                                        }
                                    }*/?>
                                </div>-->
                            </div>
                        </li>
                    <?php
                    } ?>
                </ul>
            </div>
        </div>
        <div style="float: right;">
            <button type="reset" class="button wk_mp_btn" style="float:left;margin-left: 140px !important;">
                <span><span><?php echo $helper->__('Clear') ?></span></span>
            </button>
            <button style="float:left; margin-top: -51px !important;" class="button wk_mp_btn quickcreate" title="<?php echo $helper->__('Quick Create') ?>" onclick="clickthis();" type="button" id="save_butn">
                <span><span><?php echo $helper->__('Quick Create') ?></span></span>
            </button>
        </div>
    </form>
    <br>
    <br>

    <div class="page-title">
        <h1 style="float:left;"><?php echo $helper->__('Associates Product') ?></h1>

    </div>
    <div class="wk_mp_design">
        <div class="block block-account">
            <div class="block-title">
            </div>
        </div>
        <div class="fieldset wk_mp_fieldset">
            <form action="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" method="post">
                <table cellspacing="0" class="border wk_mp_list_table">
                    <thead>
                    <tr id="wk_mp_tr_heading">
                        <th><span><?php echo $helper->__('Id') ?></span></th>
                        <th><span><?php echo $helper->__('Product Name') ?></span></th>
                        <th><span><?php echo $helper->__('Attrib. Set Name') ?></span></th>
                        <th><span>&nbsp;</span></th>
                    </tr>
                    </thead>
                    <tbody class="wk_mp_body">
                    <tr>
                        <td>
                            <input type="text" class="input-text" name="searchid" placeholder='<?php echo $helper->__('Search by id') ?>' value="<?php echo $this->getRequest()->getParam('searchid')?>"/>
                        </td>
                        <td>
                            <input type="text" class="input-text" name="s" placeholder='<?php echo $helper->__('Search by product name') ?>' value="<?php echo $this->getRequest()->getParam('s')?>"/>
                        </td>
                        <td>
                            <select name="proattrset" class="input-text">
                                <option value=""><?php echo $helper->__('Select Attribute Set') ?></option>
                                <?php foreach($this->getAllowedSets() as $set) {?>
                                    <option value="<?php echo $set['value'] ?>" <?php if($this->getRequest()->getParam('proattrset') == $set['value']) echo 'selected="selected"'?>><?php echo $set['label']?></option>
                                <?php } ?>
                            </select>
                        </td>
                        <td>
                            <button class="button" title="Save" id="save_butn" type="submit">
                                <span><span><span><?php echo $helper->__('Submit') ?></span></span></span>
                            </button>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </form>
            <?php
            if(count($this->getCollection())==0){ ?>
                <div class="fieldset wk_mp_fieldset">
                    <div class="wk_emptymsg">
                        <?php echo $helper->__('No Product Available') ?>
                    </div>
                </div>
            <?php
            } else{ ?>
                <form action="<?php echo $this->getUrl('marketplace/marketplaceaccount/assignassociate') ?>" method="post" id="form-associate" style="display: inline-block;width: 100%;">
                    <input type="hidden" class="len" name="mainid" id="productid" value="<?php echo $wholedata['id']; ?>" title="id" class="" />
                    <ul class="mp_edit_associate_ul">
                        <?php
                        $product = Mage::getModel('catalog/product')->load($wholedata['id']);
                        $productAttributeOptions = $product->getTypeInstance(true)->getConfigurableAttributesAsArray($product);
                        $attributeOptions = array();
                        $pricesByAttributeValues = array();
                        $basePrice = $product->getFinalPrice();
                        foreach ($productAttributeOptions as $productAttribute) {
                            $attr_code =  $productAttribute['attribute_code'];
                            ?>
                            <li>
                                <label class=""><?php echo $productAttribute['label']; ?>:</label>
                                <?php
                                foreach ($productAttribute['values'] as $attribute) {
                                    if ($attribute['is_percent']){
                                        $attr_price = (float)$attribute['pricing_value'] * $basePrice / 100;
                                    }
                                    else {
                                        $attr_price = (float)$attribute['pricing_value'];
                                    }
                                    ?>
                                    <div class="mp_edit_associate_div1">
                                        <div class="mp_edit_associate_div2">
                                            <label><?php echo $helper->__('Option')?> : <?php echo $attribute['store_label']; ?></label>
                                            <input type="hidden" value="<?php echo $attr_val; ?>" name="assopro[<?php echo $attr_code?>][<?php echo $attribute['value_index']?>]"/>
                                        </div>
                                        <div>
                                            <label><?php echo $helper->__('Price')?> <b><?php $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); echo  " (". Mage::app()->getLocale()->currency( $currency_code )->getSymbol().")"; ?></b>: </label>
                                            <input type="text" name="assopro[<?php echo $attr_code?>][<?php echo $attribute['value_index']?>][price]" value="<?php echo $attr_price; ?>"/>
                                        </div>
                                    </div>
                                <?php
                                }?>
                            </li>
                        <?php
                        }?>
                    </ul>
                    <table cellpadding="0" class="border list_associates wk_mp_list_table wk_mp_list_container_table" style="display: none">
                        <thead>
                        <tr class="wk_content">
                            <th style="border-left:none;">
					    			<span class="label input-checkbox">
									</span>
                            </th>
                            <th>
					    			<span class="label field-id">
										<?php echo $helper->__('Id')?>
									</span>
                            </th>
                            <th>
					    			<span class="label name-associate">
										<?php echo $helper->__('Product Name')?>
									</span>
                            </th>
                            <th>
					    			<span class="label atr-associate">
										<?php echo $helper->__('Attrib. Set Name')?>
									</span>
                            </th>
                            <th>
					    			<span class="label qty-associate">
										<?php echo $helper->__('Qty')?>
									</span>
                            </th>
                            <th>
					    			<span class="label sku-associate">
										<?php echo $helper->__('Sku')?>
									</span>
                            </th>
                            <th>
					    			<span class="label pro_status price-associate">
										<?php echo $helper->__('Price')?>
									</span>
                            </th>
                            <?php
                            foreach($configattr as $attribute) { ?>
                                <?php
                                if(isset($attribute['attribute_code'] ) == 1){ ?>
                                    <th>
								        	<span class="label qty">
												<?php echo $attribute['frontend_label']?>
											</span>
                                    </th>
                                <?php
                                }
                            } ?>
                        </tr>
                        </thead>
                    </table>
                    <table cellspacing="0" class="border list_associates wk_mp_list_table wk_mp_list_container_table">
                        <thead>
                        <tr class="wk_content">
                            <th style="border-left:none;display: none;">
					    			<span class="label input-checkbox">
									</span>
                            </th>
                            <th>
					    			<span class="label field-id">
										<?php echo $helper->__('Id')?>
									</span>
                            </th>
                            <th>
					    			<span class="label name-associate">
										<?php echo $helper->__('Product Name')?>
									</span>
                            </th>
                            <th>
					    			<span class="label atr-associate">
										<?php echo $helper->__('Attrib. Set Name')?>
									</span>
                            </th>
                            <th>
					    			<span class="label qty-associate">
										<?php echo $helper->__('Qty')?>
									</span>
                            </th>
                            <th>
					    			<span class="label sku-associate">
										<?php echo $helper->__('Sku')?>
									</span>
                            </th>
                            <th>
					    			<span class="label pro_status price-associate">
										<?php echo $helper->__('Price')?>
									</span>
                            </th>
                            <?php
                            foreach($configattr as $attribute) { ?>
                                <?php
                                if(isset($attribute['attribute_code'] ) == 1){ ?>
                                    <th>
								        	<span class="label qty">
												<?php echo $attribute['frontend_label']?>
											</span>
                                    </th>
                                    <?php
                                }
                            } ?>
                            <th>
                                <span class="label action-associate">
										<?php echo $helper->__('Action')?>
                                </span>
                            </th>
                        </tr>
                        </thead>
                        <tbody class="">
                        <?php
                        $i = 0;
                        foreach($this->getCollection() as $products){
                            // $products = Mage::getModel('catalog/product') ->load($key);
                            $i++;
                            ?>
                            <tr class="wk_row_view <?php echo $class = ($i == count($this->getCollection()))? 'wk_last_tr':''?>">
                                <input type="hidden" class="hidden_id" value="<?php echo $products->getId(); ?>" />

                                <td style="border-left:none;width: 30px;display: none;">
                                        <input type="checkbox"  checked class="assopro" name="asso_pro[<?php echo $products->getId(); ?>]" />
                                </td>
                                <td>
										<span class="label field-id">
											<?php echo $products->getId(); ?>
										</span>
                                </td>
                                <td>
										<span class="label pro_status name-associate">
											<?php echo $products->getName(); ?>
										</span>
                                </td>
                                <td>
										<span class="label pro_status atr-associate">
											<?php echo Mage::getModel('eav/entity_attribute_set')->load($products->getAttributeSetId())->getAttributeSetName(); ?>
										</span>
                                </td>
                                <td>
										<span class="label pro_status qty-associate" >
											<?php
                                            $stock_item_details = Mage::getModel('cataloginventory/stock_item')->loadByProduct($products->getId());
                                            ?>
                                            <input type="text" value="<?php echo intval($stock_item_details->getQty()); ?>" name="prod[<?php echo $products->getId()?>]"/>
										</span>
                                </td>
                                <td>
										<span class="label pro_status sku-associate">
											<?php echo $products->getSku(); ?>
										</span>
                                </td>
                                <td>
										<span class="label pro_status price-associate">
											<?php echo Mage::helper('core')->currency($products->getPrice(), true, false); ?>
										</span>
                                </td>
                                <?php
                                foreach($configattr as $attribute) {
                                    if(isset($attribute['attribute_code'] ) == 1){ ?>
                                        <td class="tdpadfirst">
							                  <span class="label pro_status atr-status" attrcode="<?php echo $products->getData($attribute['frontend_label']);?>">
													<?php
                                                    $pro= Mage::getModel('catalog/product');
                                                    $attr = $pro->getResource()->getAttribute($attribute['attribute_code']);
                                                    echo $val_id = $attr->getSource()->getOptionText($products->getData($attribute['attribute_code']));
                                                    ?>
							                  </span>
                                        </td>
                                    <?php
                                    }
                                } ?>
                                <!-- <td>
                                  <input type="hidden" class="attrcombination"/>
                                </td> -->
                                <td>
                                    <span class="label action-associate">
                                        <img src="<?php echo $this->getSkinUrl('marketplace/images/icon-trash.png'); ?>" alt="<?php echo $helper->__('Delete')?>" title="<?php echo $helper->__('Delete')?>" class="mp_delete"/>
                                    </span>
                                </td>
                            </tr>
                        <?php
                        }?>
                        </tbody>
                    </table>
                    <?php echo $this->getPagerHtml(); ?>
                    <button class="button wk_mp_btn quickcreate" onclick="return false();" title="<?php echo $helper->__('Save Associates Products') ?>" type="submit" id="save_butn">
                        <span><span><?php echo $helper->__('Save Associates Product') ?></span></span>
                    </button>
                </form>
            <?php
            }?>
        </div>
    </div>

    <div class="buttons-set">
        <p class="required">* <?php echo $helper->__('Required Fields') ?></p>
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo $helper->__('Back') ?></a>
        </p>
    </div>
    <script>
        var $wk_jq=jQuery.noConflict();
        var newCustomerProductForm1 = new VarienForm('form-quickcreate', true);
        function clickthis(){
            //var a = $wk_jq('#flag').val();
            //if(a==0){
                var test = "";
                jQuery('select.custattr').each(function(){
                    var an = $wk_jq(this).find("option:selected").text();
                    test = test + " " + an;
                });
                var array = "<?php echo $ch ?>" + test;
                var array1 = "<?php echo $configproducts->getSku();?>" + test;
                $wk_jq('#sku').val(array1);
                $wk_jq.ajax({
                    url: "<?php echo Mage::getUrl('marketplace/marketplaceaccount/verifysku');?>",
                    type: "POST",
                    data: {sku:$wk_jq('input#sku').val()},
                    dataType: 'html',
                    success:function($data){
                        $data=JSON.parse($data);
                        if($data.avl==1){

                        }
                        else{
                            var array2 = "<?php echo $configproducts->getSku();?>" + test + "product";
                            $wk_jq('#sku').val(array2);
                        }
                    }
                });
                $wk_jq('#nameproduct').val(array);
                newCustomerProductForm1.submit();
           /* }
            else{
                alert("You have reached the maximum products upload");
            }*/


        }
        (function($wk_jq){
//			$wk_jq('input#sku').change(function(){
//				var len=$wk_jq('input#sku').val();
//				var len2=len.length;
//				if(len2==0){
//					alert('<?php //echo $helper->__(" SKU cant be left empty ")?>//');
//					$wk_jq('div#skuavail').css('display','none');
//					$wk_jq('div#skunotavail').css('display','none');
//				}
//				else{
//					$wk_jq.ajax({
//						url: "<?php //echo Mage::getUrl('marketplace/marketplaceaccount/verifysku');?>//",
//						type: "POST",
//						data: {sku:$wk_jq('input#sku').val()},
//						dataType: 'html',
//						success:function($data){
//							$data=JSON.parse($data);
//							if($data.avl==1){
//								$wk_jq('div#skuavail').css('display','block');
//								$wk_jq('div#skunotavail').css('display','none');
//								$wk_jq('#save_butn').removeAttr('disabled');
//							}
//							else{
//								$wk_jq('div#skunotavail').css('display','block');
//								$wk_jq('div#skuavail').css('display','none');
//								$wk_jq("input#sku").attr('value','');
//								$wk_jq('#save_butn').attr('disabled','disabled');
//							}
//						}
//					});
//				}
//			});

            $wk_jq('.input-text').change(function(){
                var validt = $wk_jq(this).val();
                var regex = /(<([^>]+)>)/ig;
                var mainvald = validt .replace(regex, "");
                $wk_jq(this).val(mainvald);
            });

            $wk_jq(".custattr").change(function(){
                var selectedval = $wk_jq(this).val();
                $wk_jq(this).next().show();
                $wk_jq(this).next().find('span').hide()
                $wk_jq(this).next().find('input').remove()
                $wk_jq(this).next().find('#'+selectedval).show();
                if($wk_jq(this).next().find('#'+selectedval).length == 0) {
                    $wk_jq(this).next().append($wk_jq("<input class='"+selectedval+"' name='"+$wk_jq(this).attr('name')+"|price|"+$wk_jq(this).attr('id')+"|"+selectedval+"' type='text'>"));
                }
            });

            $wk_jq("#save_butn").click(function(event){
                var price=0;
                $wk_jq(".supperattr").each(function(){
                    if($wk_jq(this).find("."+$wk_jq(this).find('select').val()).val()==""){
                        price = price + parseFloat($wk_jq(this).find("."+$wk_jq(this).find('select').val()).find("b").text().split("+")[1]);
                    } else{
                        price = price + parseFloat($wk_jq(this).find("."+$wk_jq(this).find('select').val()).val());
                    }
                });
                $wk_jq("#form-quickcreate").find(".fieldset").find(".finalprice").remove();
                $wk_jq("#form-quickcreate").find(".fieldset").prepend("<input class='finalprice' name='price' value='"+price+"' type='hidden'>")
                /*if($wk_jq(".supperattr").find("input").length==0){
                    alert('<?php //echo $helper->__(" This Combination of attributes already exists ")?>');
                    event.preventDefault();
                }*/
            });

            $wk_jq("body").delegate('.nicEdit-main',"blur",function(){
                var x = $wk_jq(this).text()
                $wk_jq(this).parent().parent().children('textarea').text(x);
            });

            $wk_jq('.mp_delete').click(function(){
                var id=$wk_jq(this).parents('.wk_row_view').find('.hidden_id').val();
                var dicisionapp=confirm('<?php echo $helper->__(" Are you sure you want to delete this associate product ? ")?>');
                if(dicisionapp==true)
                    window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/deleteassociate/') ?>".concat("id/",id);
            });
        })($wk_jq);
    </script>
<?php
}else{
    echo "<h2 class='wk_new_msg'>".$helper->__("To BECOME SELLER PLEASE CONTACT TO ADMIN.")."</h2>";
}
    $var = Mage::app()->getRequest()->getParam('id');
    Mage::getSingleton('core/session')->setSomeSessionVar($var);

?>
