
<?php
$collection = Mage::getResourceModel('catalog/product_attribute_collection')->addVisibleFilter();
$collection->getSelect()->where('is_user_defined=1');
$collection->getSelect()->where('is_configurable=1');
$collection->getSelect()->where('is_visible=1');
$collection->getSelect()->where('is_global=1');
$helper = Mage::helper('marketplace');
$attributes = Mage::getModel('catalog/product_attribute_api')->items($this->getRequest()->getParam('set'));

$uri = $_SERVER['REQUEST_URI'];
$segment = explode("/", $uri);
$new_product = '';
$simple_product = '';
foreach ($segment as $params) {
    if ($params == 'new') {
        $new_product = 'new';
    }
    if ($params == 'marketplaceaccount') {
        $simple_product = 'marketplaceaccount';
    }
}
?>
<input id="new_product" value="<?php echo $new_product; ?>" type="hidden">
<input id="simple_product" value="<?php echo $simple_product; ?>" type="hidden">

<!-- production -->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plupload1.5/plupload.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plupload1.5/plupload.gears.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plupload1.5/plupload.silverlight.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plupload1.5/plupload.flash.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plupload1.5/plupload.browserplus.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plupload1.5/plupload.html4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/plupload1.5/plupload.html5.js'); ?>"></script>

<form method="post" id="form-super-attribute">
    <div class="buttons-set">
        <p class="required">* <?php echo $helper->__('Required Fields') ?></p>
        <p class="back-link">
            <a style="margin-top: -120px; font-size: 15px" href="javascript:;" onclick="javascript: window.history.back();" class="left"> <?php echo $helper->__('Back') ?></a>
        </p>
    </div>
	<div class="page-title">
		<h1 style="float:left;"><?php echo $helper->__('Select Configurable Attribute') ?></h1>

	</div>
	<div class="wk_mp_design">
		<div class="block block-account">	
			<div class="block-title">	
				<strong><span><h4 style="display: none"><?php echo $helper->__('Configurable Attribute') ?></h4></span></strong>
			</div>
		</div>
		<div class="fieldset wk_mp_fieldset">
			<?php 
			foreach($attributes as $attribute) {
				$data = Mage::getModel('catalog/resource_eav_attribute')->load($attribute['attribute_id']);
				if(($data['frontend_input'] == 'select' || $data['frontend_input'] == 'multiselect') && $data['is_user_defined'] == 1 && $data['is_configurable'] == 1&& $data['is_visible'] == 1 && $data['is_global'] == 1) { ?>
					<div class="supattrselect">
						<input class="validate-one-required-by-name" type="checkbox" id="attribute[<?php echo $data['attribute_code']; ?>]" value="<?php echo $data['attribute_code']; ?>" name="superattributeselect"/>
						<span><?php echo $data['frontend_label']; ?></span>
					</div>
				<?php 
				} 
			} ?>
		</div>
	</div>
    <button class="button wk_mp_btn configattr" title="<?php echo $helper->__('Create Configurable Product') ?>" type="submit" style="clear:none">
        <span><span><?php echo $helper->__('Create Configurable Product') ?></span></span>
    </button>
    <button type="reset" class="button wk_mp_btn" style="clear:none">
        <span><span><?php echo $helper->__('Clear') ?></span></span>
    </button>

</form>

<?php
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
$currency = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();
$currency_symbol = trim($currency);
$customerid=Mage::getSingleton('customer/session')->getCustomerId();
$isPartner= Mage::getModel('marketplace/userprofile')->isPartner($customerid);
if($isPartner==1){?>
<!--	<script type="text/javascript">-->
<!--	if (typeof jQuery == 'undefined'){-->
<!--	    document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));-->
<!--	}-->
<!--	</script> -->
	<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<script type="text/javascript">
		bkLib.onDomLoaded(function() {
		    new nicEditor({fullPanel : true}).panelInstance('description');
		    /*new nicEditor({fullPanel : true}).panelInstance('short_description');*/
		});
	</script>
	<?php 
	$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
	$procollection = Mage::getResourceModel('marketplace/product_collection');
	$procollection->getSelect()->where('userid ='.$customerId);
	$collection = Mage::getModel('sales/order')->getCollection();
	echo $this->getMessagesBlock()->getGroupedHtml();
	$products = $this->getProducts();
	if (isset($_SESSION['new_products_errors'])) {
		$style="";
		$name = (isset($_SESSION['new_products_errors']['name'])) ? $_SESSION['new_products_errors']['name'] : '';
		$description = (isset($_SESSION['new_products_errors']['description'])) ? $_SESSION['new_products_errors']['description'] : '';
		$short_description = (isset($_SESSION['new_products_errors']['short_description'])) ? $_SESSION['new_products_errors']['short_description'] : '';
		$price = (isset($_SESSION['new_products_errors']['price'])) ? $_SESSION['new_products_errors']['price'] : '';
		$weight = (isset($_SESSION['new_products_errors']['weight'])) ? $_SESSION['new_products_errors']['weight'] : '';
		$stock = (isset($_SESSION['new_products_errors']['stock'])) ? $_SESSION['new_products_errors']['stock'] : '';unset($_SESSION['new_products_errors']);
	} 
	else {
		$style="display:block;";
		$name = '';
		$description = '';
		$short_description = '';
		$price = '';
		$weight = '';
		$stock = '';
		$sku = '';
	}
		
	$categories = Mage::getModel('catalog/category')->getCollection()->addAttributeToSelect('*')->addIsActiveFilter();
	$allcatid = array();
	$k=0;
	foreach ($categories as $c) {
	   $allcatid[$k] = $c->getId();
	   $k++;
	}
	$finalcat=array_shift($allcatid);
	$partner=Mage::getModel('marketplace/userprofile')->getPartnerProfileById($customerid);
	?>
	<div class="prdouctbackground" style="display: none" >
		<form action="<?php echo $this->getUrl('marketplace/marketplaceaccount/configproduct') ?>" enctype="multipart/form-data" method="post" id="form-customer-product-new" >
			<div class="page-title">
				<h1 style="float:left;"><?php echo $helper->__('Add New Configurable Product') ?></h1>

<!--				<button class="button wk_mp_btn " title="--><?php //echo $helper->__('Add Associate Product') ?><!--" type="submit" id="save_butn">-->
<!--					<span><span>--><?php //echo $helper->__('Add Associate Product') ?><!--</span></span>-->
<!--				</button>-->
			</div>
			<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
			<input type="hidden" name="attribute_set_id" id="attribute_set_id" value="<?php echo $this->getRequest()->getParam('set')!=''? $this->getRequest()->getParam('set'):4;  ?>" />
			<input type="hidden" name="type_id" id="producttype" value="<?php echo $this->getRequest()->getParam('type')?>" />
			<input type="hidden" class="len" name="supperattr" id="supperattr" value="supperattr"/>
			<input type="hidden"  name="wstoreids" id="wstoreids" value="<?php echo Mage::app()->getStore()->getStoreId(); ?>" title="wstoreids" />
			<div class="wk_mp_design">
				<div class="block block-account">	
					<div class="block-title">	
						<strong><span><h4><?php echo $helper->__('Add Configurable Product') ?></h4></span></strong>
					</div>
				</div>
				<div class="fieldset wk_mp_fieldset">
					<ul  class="form-list" id="wk_bodymain">
                        <li>
                            <label class="required"><em>*</em><?php echo $helper->__('Status') ?>:</label>
                            <div class="input-box">
                                <input style="width: 50px" type="radio" class="" name="status" id="status"  value="1" /><?php echo $helper->__("Enable"); ?>
                                <input style="width: 50px" type="radio" class="" name="status" id="status" value="2" checked='checked'/><?php echo $helper->__("Disable"); ?>
                            </div>
                        </li>
                        <li>
							<label><?php echo $helper->__('Product Category') ?>:<em style="color:red">*</em></label>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_category')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_category') ?>"/>
							<?php
							} ?>
							<div class="wk_field wk_category">
								<div class="wk_for_validation">
									<div id="wk_category_label"><?php echo $helper->__("CATEGORIES"); ?></div>
			            			<?php
			            			if(Mage::getStoreConfig('marketplace/marketplace_options/categoryids')){
			            				$storeconfig_catids = explode(',',trim(Mage::getStoreConfig('marketplace/marketplace_options/categoryids')));
			            				foreach($storeconfig_catids as $storeconfig_catid)	{
			            					$cat_model = Mage::getModel("catalog/category")->load($storeconfig_catid); ?>
											<div class="wk_cat_container">
												</span><span class="wk_foldersign"></span>
												<span class="wk_elements wk_cat_name"><?php echo $cat_model->getName() ?></span>
												<input class="wk_elements" type="checkbox" name="category[]" value='<?php echo $cat_model['entity_id'] ?>'/>
											</div> 
									   		<?php 
			            				}
			            			}else{
				            			$Mar_lef = 0;$count = 0;
										$category_helper = Mage::helper("catalog/category");
										$category_model = Mage::getModel("catalog/category");
										$_categories = $category_helper->getStoreCategories();
										foreach($_categories as $_category)	{
											$count++;
										 	if(count($category_model->getResource()->getAllChildren($category_model->load($_category['entity_id'])))-1 > 0){ ?>
												<div class="wk_cat_container" style="margin-left:0px;">
													<span class="wk_plus">
													</span><span class="wk_foldersign"></span>
													<span class="wk_elements wk_cat_name"><?php echo $_category->getName() ?></span>
													<input class="wk_elements" type="checkbox" name="category[]" value='<?php echo $_category['entity_id'] ?>'/>
												</div>
												<?php
											}else { ?>
												<div class="wk_cat_container">
													</span><span class="wk_foldersign"></span>
													<span class="wk_elements wk_cat_name"><?php echo $_category->getName() ?></span>
													<input class="wk_elements" type="checkbox" name="category[]" value='<?php echo $_category['entity_id'] ?>'/>
												</div> 
										   		<?php 
											}
									    } 
									}?>
								</div>
							</div>
						</li>
						<li>
							<label for="name" class="rightgap"><?php echo $helper->__('Product Name :')?><em style="color:red">*</em></label>
								<span class="required starimp"></span>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_name')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_name') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<input type="name" class="required-entry input-text" name="name" id="name" />
							</div>
						</li>
						<li>
							<label for="description" class="rightgap"><?php echo $helper->__('Description :') ?><em style="color:red">*</em></label>
							<span class="required starimp"></span>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_des')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_des') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<textarea name="description" class="required-entry " id="description" rows="5" cols="75" ></textarea>
							</div>
                            <div class="validation-advice des-validate" style="display: none">This is a required field.</div>
						</li>

						<li>
							<label for="sku" class="rightgap"><?php echo $helper->__('SKU :') ?><em style="color:red">*</em></label><span class="required starimp"></span>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_sku')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_sku') ?>"/>
							<?php
							} ?>
							<div class="input-box">
									<input name="sku" id="sku" class="required-entry input-text" />
							</div>
							<div id="skuavail" >
								<span class="success-msg skuavailable" style="color:#008000"><?php echo $helper->__('SKU Available') ?></span>
							</div>
							<div id="skunotavail" >
								<span class="error-msg skunotavailable" style="color:red"><?php echo $helper->__('SKU Already Exist') ?></span>
							</div>
						</li>
						<li>
							<label class="required"><em>*</em><?php echo $helper->__('Price') ?><b><?php  echo  " (". $currency_symbol .")"; ?></b>:</label><span class="required starimp"></span>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_price')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_price') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<input type="price" class=" required-entry input-text" name="price" id="price" />
							</div>
						</li>
						<li>
							<label ><?php echo $helper->__('Special Price') ?><b><?php echo  " (". $currency_symbol.")"; ?></b>:</label>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_sprice')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_sprice') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<input type="special_price" class="widthinput input-text" name="special_price" id="special_price" />
							</div>
						</li>
						<li>
							<label ><?php echo $helper->__('Special Price From') ?>:</label>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_sdate')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_sdate') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<input name="special_from_date" id="special_from_date" class="input-text"/>
							</div>
						</li>
						<li>
							<label ><?php echo $helper->__('Special Price To') ?>:</label>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_edate')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_edate') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<input name="special_to_date" id="special_to_date" class="input-text"/>
							</div>
						</li>
                        <li style="display: none;">
                            <label ><?php echo $helper->__('Set Product as New from Date') ?>:</label>

                            <div class="input-box">
                                <input name="news_from_date" id="news_from_date" class="input-text"/>
                            </div>
                        </li>
                        <li style="display: none;">
                            <label class="required"><em>*</em><?php echo $helper->__('Popular') ?>:</label>
                            <div class="input-box">
                                <input style="width: 50px" type="radio" class="" name="popular" id="popular"  value="0" checked="checked"/><?php echo $helper->__("No"); ?>
                                <input style="width: 50px" type="radio" class="" name="popular" id="popular" value="1" /><?php echo $helper->__("Yes"); ?>
                            </div>
                        </li>
						<li>
							<label class="required"><em>*</em><?php echo $helper->__('Stock Availability') ?>:</label>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_stock')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_stock') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<select id="inventory_stock_availability" class="select" name="is_in_stock">
									<option value="1"><?php echo $helper->__("In Stock"); ?></option>
									<option value="0"><?php echo $helper->__("Out of Stock"); ?></option>
								</select>
							</div>
						</li>
						<li style="display: none;">
							<label class="required"><em>*</em><?php echo $helper->__('Tax Class') ?>:</label>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_tax')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_tax') ?>"/>
							<?php
							} ?>
							<div class="input-box">
								<select id="tax_class_id" class=" required-entry required-entry select" name="tax_class_id">
									<option value="0"><?php echo $helper->__('None')?></option>
									<?php
										$taxes=Mage::getModel('tax/class')->getCollection()
													->addFieldToFilter('class_type',array('eq'=>'PRODUCT'));
										foreach($taxes as $tax){
									?>
									<option value="<?php echo $tax->getId() ?>"><?php echo $tax->getClassName()?></option>
									<?php } ?>
							</select>
							</div>
						</li>
						<li>
							<label for="file" class="rightgap"><?php echo $helper->__('Image (Select Multiple)') ?><em style="color:red">*</em></label><span class="required starimp"></span>
							<?php
							if(Mage::getStoreConfig('marketplace/marketplace_products/product_hint_status') && Mage::getStoreConfig('marketplace/marketplace_products/product_image')){?>
								<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::getStoreConfig('marketplace/marketplace_products/product_image') ?>"/>
							<?php
							} ?>
<!--							<div  class="input-box">-->
<!---->
<!--								<input type="file" name="images[]" class="images" size="33" multiple="multiple" >-->
<!---->
<!--							</div>-->
							<div id="container">
								<div id="filelist"></div>
								<br />
								<a id="pickfiles" href="javascript:;">[Select files]</a>
								<a id="uploadfiles" href="javascript:;">[Upload files]</a>
							</div>
						</li>
						<?php echo $this->getChildHtml(); ?>
					</ul>
				</div>	
			</div>
            <div>
                <button style="margin-right: 350px; margin-top: 10px;" type="reset" class="button wk_mp_btn" id="button_edit_seller" onclick="canceltest();">
                    <span><span><?php echo $helper->__('Clear') ?></span></span>
                </button>
                <a id="save_butn">Continue</a>
            </div>
		</form>
	</div>		
	<!--
	end new product
	-->		
	<script type="text/javascript">		
		var $wk_jq = jQuery.noConflict();
		var newSuperAttributeForm = new VarienForm('form-super-attribute', true);
        var newCustomerProductForm = new VarienForm('form-customer-product-new', true);
        //alert(newCustomerProductForm.validator.validate());
//      jQuery('form.form-customer-product-new').each(function(){
//           var newCustomerProductForm = new VarienForm(this, true);
//      });
//        if(jQuery('#prdouctbackground').hasClass('save_test')){
//            var newCustomerProductForm = new VarienForm('form-customer-product-new', true);
//            alert('test');
//        }

		$wk_jq( "#special_from_date").datepicker({'dateFormat':'mm:dd:yy'});
		$wk_jq( "#special_to_date" ).datepicker({'dateFormat':'mm:dd:yy'});
        $wk_jq( "#news_from_date" ).datepicker({'dateFormat':'mm:dd:yy'});
        var currentDate = new Date();
        var day = currentDate.getDate();
        var month = currentDate.getMonth() + 1;
        var year = currentDate.getFullYear();
        /*var today = year + ":" + month + ":" + day;*/
        var today = month + ":" + day + ":" + year;
        if ($wk_jq('#new_product').val() == 'new' && $wk_jq('#simple_product').val() == 'marketplaceaccount') {
            $wk_jq('#news_from_date').val(today);
        }

		var i=2;
        function canceltest(){
            $i=1;
            nicEditors.findEditor("description").setContent("");
            //nicEditors.findEditor("short_description").setContent("");
            jQuery(".remove-test").remove();

        }
		function showOtherImage(){
			var newdiv = document.createElement('div');
			newdiv.setAttribute("id","childDiv"+i);
			newdiv.innerHTML = "<input type='file' name='images"+i+"' /><input type='radio'  onClick='defaultimagevalue(this)'  value=''  class='defaultimage' name='defaultimage'><span class='defaultimageset'><?php echo $helper->__(' Base image '); ?></span><a href=\"javascript:;\" onclick=\"removeEvent('childDiv"+i+"')\"><?php echo $helper->__(' Remove '); ?></a>";
			var ni = document.getElementById('otherimages');
			ni.appendChild(newdiv);
			i++;
		}
		function removeEvent(divNum){
			var d = document.getElementById('otherimages');
			var olddiv = document.getElementById(divNum);
			d.removeChild(olddiv);
			i--;
		}
		function defaultimagevalue(object){
			var strs=$wk_jq(object).prev('input').val().split('\\'); 
		    $wk_jq(object).val(strs[strs.length-1]);
		}
		function catchanged(){
            jQuery("#wk_cp_cat_edited").val(1);
		}

		(function($wk_jq){
			$wk_jq('#save_butn').click(function(e){
                var descrip1 = nicEditors.findEditor("description").getContent();
                //var sdescrip1 = nicEditors.findEditor("short_description").getContent();
                if(descrip1=='<br>'){
                    jQuery('.des-validate').addClass('test-view');
                }
                else{
                    jQuery('.des-validate').removeClass('test-view');
                }
                /*if(sdescrip1=='<br>'){
                    jQuery('.sdes-validate').addClass('test-view');
                }
                else{
                    jQuery('.sdes-validate').removeClass('test-view');
                }*/
				//if(newCustomerProductForm.validator.validate() && descrip1!='<br>' && sdescrip1!='<br>'){
                if(newCustomerProductForm.validator.validate() && descrip1!='<br>'){
                    var shippingcheck=0;
                    $wk_jq(".shipping_custom").each(function(){
                        if($wk_jq(this).find("input:checkbox:checked").val()!='' && typeof $wk_jq(this).find("input:checkbox:checked").val()!='undefined')
                            shippingcheck = 1;
                    });
                    var check = 0;
                    $wk_jq(".wk_category").each(function(){
                        if($wk_jq(this).find("input:checkbox:checked").val()!='' && typeof $wk_jq(this).find("input:checkbox:checked").val()!='undefined')
                            check = 1;
                    });

                    if(shippingcheck==1 && check==1 && $i!=1) {
                        var descrip = nicEditors.findEditor("description").getContent();
                        //var sdescrip = nicEditors.findEditor("short_description").getContent();
                        //var regex = /(&lt([^>]+)&gt)/ig;
                        var regex = /<script(.+?)<\/script>/g;
                        var result = descrip.replace(regex, "");
                        result = result.replace(/script/g, '');
                        nicEditors.findEditor("description").setContent(result);
                        /*var sresult = sdescrip.replace(regex, "");
                        sresult = sresult.replace(/script/g, '');
                        nicEditors.findEditor("short_description").setContent(sresult);*/
                        $wk_jq('#description').text(result);
                        //$wk_jq('#short_description').text(sresult);
                        $wk_jq('#save_butn').text('<?php echo $helper->__("Saving..")?>');
                        $wk_jq('.button').css('opacity', '0.7');
                        $wk_jq('.button').css('cursor', 'default');
                        $wk_jq('.button').attr('disabled', 'disabled');
                        $wk_jq('#save_butn').css('pointer-events', 'none');
                        $wk_jq('#save_butn').css('cursor', 'default');
                        $wk_jq('#save_butn').css('opacity', '0.7');
                        $wk_jq('#form-customer-product-new').submit();
                    }
                    else{
                        if(shippingcheck!=1 && check!=1){
                            alert("Please choose at least one shipping method and choose category");
                        }else{
                            if(shippingcheck!=1){
                                alert("Please choose at least one shipping method");
                            }
                            else if(check!=1){
                                alert("Please choose category");
                            } else {
                                alert("Please upload images");
                            }
                        }
                    }
				}
			});

			$wk_jq('.input-text').change(function(){
				var validt = $wk_jq(this).val();
				var regex = /(<([^>]+)>)/ig;
				var mainvald = validt .replace(regex, "");
				$wk_jq(this).val(mainvald);	
		    })
			
			$wk_jq(".dumimg").change(function(){
				$wk_jq( ".defaultimage" ).prop( "checked", false );
			});

			$wk_jq('input#sku').change(function(){
				var len=$wk_jq('input#sku').val();
				var len2=len.length;
				if(len2==0){
					alert('<?php echo $helper->__(" SKU can\'t be left empty ")?>');
					$wk_jq('div#skuavail').css('display','none');
					$wk_jq('div#skunotavail').css('display','none');
				}
				else{
					$wk_jq.ajax({
						url: "<?php echo Mage::getUrl('marketplace/marketplaceaccount/verifysku');?>",
						type: "POST",
						data: {sku:$wk_jq('input#sku').val()},
						dataType: 'html',
						success:function($data){
							$data=JSON.parse($data);
							if($data.avl==1){
								$wk_jq('div#skuavail').css('display','block');
								$wk_jq('div#skunotavail').css('display','none');
							}
							else{
								$wk_jq('div#skunotavail').css('display','block');
								$wk_jq('div#skuavail').css('display','none');
								$wk_jq("input#sku").attr('value','');
							}
						}
					});
				}
			});

			$wk_jq(".configattr").click(function(event){
				event.preventDefault();
				var superattribute='';
				$wk_jq(".supattrselect").each(function(){
					if($wk_jq(this).find("input:checkbox:checked").val()!='' && typeof $wk_jq(this).find("input:checkbox:checked").val()!='undefined')
						superattribute =superattribute + $wk_jq(this).find("input:checkbox:checked").val()+",";
				});
				$wk_jq("#supperattr").val(superattribute);
				if(superattribute==''){
					alert("<?php echo $helper->__(' Please Select Options ')?>");
				}else{
					$wk_jq(".prdouctbackground").show();
					$wk_jq(this).parent().hide();
					$wk_jq.each( superattribute.split(","), function( key, value ) {
					 	$wk_jq("#"+value).parents("li").remove();
					});
				}
			});

			$wk_jq("#wk_bodymain").delegate('.wk_plus ,.wk_plusend,.wk_minus, .wk_minusend ',"click",function(){
				var thisthis=$wk_jq(this);	
				if(thisthis.hasClass("wk_plus") || thisthis.hasClass("wk_plusend")){
					if(thisthis.hasClass("wk_plus"))
						thisthis.removeClass('wk_plus').addClass('wk_plus_click');
					if(thisthis.hasClass("wk_plusend"))
						thisthis.removeClass('wk_plusend').addClass('wk_plusend_click');
					thisthis.prepend("<span class='wk_node_loader'></span>");
					$wk_jq.ajax({
						url  	:   "<?php echo $this->getUrl('marketplace/marketplaceaccount/categorytree/');?>",
						type 	:   "POST",
						data 	:   {CID:thisthis.siblings("input").val(),
									ML:thisthis.parent(".wk_cat_container").css("margin-left").replace("px","")},
						dataType:   "html",
						success :   function(content){
							var newdata=  $wk_jq.parseJSON(content);
							len= newdata.length;
							var pxl= parseInt(thisthis.parent(".wk_cat_container").css("margin-left").replace("px",""))+20;
							thisthis.find(".wk_node_loader").remove();
							if(thisthis.attr("class") == "wk_plus")
							thisthis.attr("class","wk_minus");
							if(thisthis.attr("class") == "wk_plusend")
								thisthis.attr("class","wk_minusend");
							if(thisthis.attr("class") == "wk_plus_click")
								thisthis.attr("class","wk_minus");
							if(thisthis.attr("class") == "wk_plusend_click")
								thisthis.attr("class","wk_minusend");
						    for(i=0;i<len; i++){     
								id=newdata[i].id;
								nam=newdata[i].name;
								if(newdata[i].counting ==0){
									thisthis.parent(".wk_cat_container").after('<div class="wk_removable wk_cat_container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk_no"></span><span class="wk_foldersign"></span><span class="wk_elements wk_cat_name">'+ nam +'</span><input class="wk_elements" type="checkbox" name="category[]" value='+ id +'></div>');
								}else{
									thisthis.parent(".wk_cat_container").after('<div class="wk_removable wk_cat_container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk_plusend"></span><span class="wk_foldersign"></span><span class="wk_elements wk_cat_name">'+ nam +'</span><input class="wk_elements" type="checkbox" name="category[]" value='+ id +'></div>');   
								}
							}
							thisthis.parent(".wk_cat_container").nextAll().slideDown(300);
						}
					});			
				}
				if(thisthis.hasClass("wk_minus") || thisthis.hasClass("wk_minusend")){
					if(thisthis.attr("class") == "wk_minus")
						thisthis.attr("class","wk_plus");
					if(thisthis.attr("class") == "wk_minusend")
						thisthis.attr("class","wk_plusend");
					var thiscategory = thisthis.parent(".wk_cat_container");
					var marg= parseInt(thiscategory.css("margin-left").replace("px",""));
					while(thiscategory.next().hasClass("wk_removable")){
					  
					if(parseInt(thiscategory.next().css("margin-left").replace("px",""))>marg)
						thiscategory.next().slideUp("slow",function(){$wk_jq(this).remove();});
						thiscategory = thiscategory.next();	
						if(typeof thiscategory.next().css("margin-left")!= "undefined"){
							if( marg==thiscategory.next().css("margin-left").replace("px",""))
							{
							  break;
							}
						}
					}
				}		
			});

			$wk_jq("body").delegate('.nicEdit-main',"blur",function(){
				var x = $wk_jq(this).text()
				$wk_jq(this).parent().parent().children('textarea').text(x);		
			});
		})($wk_jq);
	</script>
	<script type="text/javascript">
		// Custom example logic

//		var uploader = new plupload.Uploader({
//			runtimes : 'html5,flash,silverlight,html4',
//			browse_button : 'pickfiles', // you can pass an id...
//			container: document.getElementById('container'), // ... or DOM Element itself
//			url : 'upload.php',
//			flash_swf_url : '<?php //echo $this->getSkinUrl('js/plupload/Moxie.swf'); ?>//',
//			silverlight_xap_url : '<?php //echo $this->getSkinUrl('js/plupload/Moxie.xap'); ?>//',
//
//			filters : {
//				max_file_size : '10mb',
//				mime_types: [
//					{title : "Image files", extensions : "jpg,gif,png"},
//					{title : "Zip files", extensions : "zip"}
//				]
//			},
//
//			init: {
//				PostInit: function() {
//					document.getElementById('filelist').innerHTML = '';
//
//					document.getElementById('uploadfiles').onclick = function() {
//						uploader.start();
//						return false;
//					};
//				},
//
//				FilesAdded: function(up, files) {
//					plupload.each(files, function(file) {
//						document.getElementById('filelist').innerHTML += '<div id="' + file.id + '">' + file.name + ' (' + plupload.formatSize(file.size) + ') <b></b></div>';
//					});
//				},
//
//				UploadProgress: function(up, file) {
//					document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
//				},
//
//				Error: function(up, err) {
//					document.getElementById('console').appendChild(document.createTextNode("\nError #" + err.code + ": " + err.message));
//				}
//			}
//		});
//		uploader.init();
		// Custom example logic

		function $wk_jq(id) {
			return document.getElementById(id);
		}

        var $i=1;
		var uploader = new plupload.Uploader({
			runtimes : 'gears,html5,flash,silverlight,browserplus',
			browse_button : 'pickfiles',
			container: 'container',
			max_file_size : '10mb',
			url : '<?php echo $this->getUrl('marketplace/marketplaceaccount/uploadImages') ?>',
			//resize : {width : 320, height : 240, quality : 90},
			flash_swf_url : '<?php echo $this->getSkinUrl('js/plupload1.5/plupload.flash.swf'); ?>',
			silverlight_xap_url : '<?php echo $this->getSkinUrl('js/plupload1.5/plupload.silverlight.xap'); ?>',
			filters : [
				{title : "Image files", extensions : "jpg,gif,png"},
				{title : "Zip files", extensions : "zip"}
			]
		});

		uploader.bind('Init', function(up, params) {
			//$('filelist').innerHTML = "<div>Current runtime: " + params.runtime + "</div>";
		});

		uploader.init();

		uploader.bind('FilesAdded', function(up, files) {
			for (var i in files) {
				if(files[i].id) {
                    $wk_jq('filelist').innerHTML += '<div class="remove-test" id="' + files[i].id + '">' + files[i].name + ' (' + plupload.formatSize(files[i].size) + ') <b></b></div>';
				}
			}
		});

		uploader.bind('UploadProgress', function(up, file) {
            $wk_jq(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
		});

		uploader.bind('FileUploaded', function(up, file,response) {
            if($i==1){
                var obj = JSON.parse(response.response);
                $wk_jq(file.id).innerHTML = '<img height="150" style="max-width:250px" src="'+obj.web_url+'"/>' +
                '<div class="base_img_div"><input type="hidden" value="'+obj.real_url+'" name="upload_images[]"/>'+
                '<p><input id="defaultimage" type="radio" name="defaultimage"  checked="checked" class="'+$i+'" value="'+obj.real_url+'"/><span class="base_img_txt">Base Image</span></p>'+
                '<p><span class="pos_img_txt">Position</span><input type="text" class="position_img" width="10" name="position['+obj.web_url+']" value="'+$i+'"></p></div>';
                $i=$i+1;
            }
            else{
                var obj = JSON.parse(response.response);
                $wk_jq(file.id).innerHTML = '<img height="150" style="max-width:250px" src="'+obj.web_url+'"/>' +
                '<div class="base_img_div"><input type="hidden" value="'+obj.real_url+'" name="upload_images[]"/>'+
                '<p><input id="defaultimage" type="radio" name="defaultimage"  class="'+$i+'" value="'+obj.real_url+'"/><span class="base_img_txt">Base Image</span></p>'+
                '<p><span class="pos_img_txt">Position</span><input type="text" class="position_img" width="10" name="position['+obj.web_url+']" value="'+$i+'"></p></div>';
                $i=$i+1;
            }




        });
        $wk_jq('uploadfiles').onclick = function() {
			uploader.start();
			return false;
		};

	</script>
	<?php 
}else{
	echo $helper->__("<h2 style='color:#ff0000;font-weight:600'>FOR BECOME SELLER CONTACT TO ADMIN..</h2>");
}?>
