<?php  
$feeds=$this->getFeed();
$partner=$this->getProfileDetail();
$helper = Mage::helper('marketplace');
$userid=$partner['mageuserid'];
$customer=Mage::getModel('customer/customer')->load($userid);
$locsearch=$partner->getcomplocality()==''? Mage::getModel('directory/country')
			->load($partner->getcountrypic())->getName():$partner->getcomplocality();
$countryflag=$this->getSkinUrl('marketplace/images/country/countryflags/')
				.strtoupper($partner->getcountrypic()==""?"XX":
				$partner->getcountrypic()).".png";
$baseurl=$this->getUrl('marketplace/seller');
				
?>
<script type="text/javascript">
	if (typeof jQuery == 'undefined'){
		document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
</script> 
<div class="wk_mp_design design-test">
	<!--<div class="block block-account" >
		<div class="block-title">
			<strong><span><h4><?php /*echo $helper->__("ABOUT SELLER") */?></h4></span></strong>
		</div>
	</div>-->
	<div class="fieldset wk_mp_fieldset" style="padding: 5px 10px; ">
		<div id="info" class="block-content">
			<div class="wk_seller section first">	
				<!--<div class="storename section">
					<span class="wk_storename_icon wk_icon"></span>
					<a class="store-name" href="<?php /*echo $baseurl."profile/".$partner->getProfileurl();*/?>">
						<?php /*echo $customer->getName(); */?>
					</a>
				</div>-->
				<div class="section">
					<span style="font-weight: bold"><?php echo $helper->__('Shop Name:');?></span>
					<span class="data"><?php echo $partner->getshoptitle();?></span>
				</div>
				<?php if($partner->gethide()!=1):?>
					<div class="section">
						<span style="font-weight: bold"><?php echo $helper->__('Contact Number:');?></span>
						<?php $country_code =  $partner->getcountrymobile();
						$collections=Mage::getModel('directory/country')->getCollection()->addFieldToFilter('country_id',$country_code);
						$country_name = Mage::app()->getLocale()->getCountryTranslation($country_code);
						$count = count($collections);
						if($count!=1){?>
							<span class="data"><?php echo $partner->getareamobile()." ".$partner->getcontactnumber();?></span>
							<?php
						}
						foreach ($collections as $row){?>
							<span class="data"><?php echo '+'.$row['phone_country']." ".$partner->getareamobile()." ".$partner->getcontactnumber();?></span>
						<?php } ?>
					</div>
				<?php endif; ?>
				<div class="section" >
					<span style="font-weight: bold"><?php echo $helper->__('Shop Description:');?></span>
					<div class="data shop-description"><?php echo $partner->getcompdesi();;?></div>
				</div>
				<?php if($partner->getcomplocality()!=''){ ?>
					<div class="wefrom section">
						<span class="wk_storeloc_icon wk_icon"></span>
						<span><?php echo $partner->getcomplocality();?></span>
						<!--<span><?php /*echo $locsearch; */?></span>-->
						<!--<a class="cont-name" title="<?php /*echo $helper->__('Search') */
						?>" href="<?php /*echo  $baseurl."location/".$partner->getProfileurl()."?q=".$locsearch*/
						?>" target="_blank">
						<span><?php /*echo $locsearch; */
						?></span>
					</a>-->
						<!--<a title="<?php /*echo $helper->__('View Map') */
						?>" target="_blank" href="<?php /*echo  $baseurl."location/".$partner->getProfileurl()."?q=".$locsearch*/
						?>">
						<img class="piccountry" title="<?php /*echo $helper->__('View Map') */
						?>" src="<?php /*echo $countryflag;  */
						?>" />
					</a>-->
					</div>
				<?php } ?>
				<div class="wk_feedback section">
					<span class="wk_feedback_icon wk_icon"></span>
					<a class="store-name" href="<?php echo $baseurl."feedback/".$partner->getProfileurl()?>">
						<strong><?php echo $feeds['totalfeed']; ?>% </strong><?php echo $helper->__('Positive Reviews') ?>
					</a>
				</div>
				<div class="wk_ratings section">
					<span class="wk_rating_icon wk_icon"></span>
					<a class="store-name" href="<?php echo $baseurl."feedback/".$partner->getProfileurl()?>">
						<strong><?php echo $feeds['feedcount']; ?> </strong><?php echo $helper->__('Ratings') ?>
					</a>
				</div>

				<div class="connect section">  
<!--					<span class="wk_connect_icon wk_icon"></span> -->
					<span style="font-weight: bold"><?php echo $helper->__('Connect with Us:') ?></span>
					<ul>      
						
						<li class="ask_que">			
							<span class="icon_social"> <img src="<?php echo $this->getSkinUrl('marketplace/images/icon_mail.png') ?>" alt=""></span>
							<a id="askque">
								<?php echo $helper->__('Mail Us') ?>
							</a>	
							<div id="ask_data">
								<div class="modal_header">
									<h4 class="modal-title"><?php echo $helper->__('Ask Question to me') ?></h4>
									<span  class="wk_close" >x</span>
									<span  class="wk_clear" ></span>
								</div>
								<form id="ask_form" method="post" >
									<div class="modal-body">
										<span class="label"><?php echo $helper->__('Email') ?> :</span><input type="text" name="email" class="queryemail form-control"/>
										<span class="label"><?php echo $helper->__('Subject') ?> :</span><input type="text" name="subject" class="form-control"/>
										<span class="label"> <?php echo $helper->__('Ask') ?> :</span><textarea  name="ask" class="queryquestion form-control"></textarea>
										<input type="hidden" name="seller-id" value="<?php echo $userid;?>"/>
										<?php 
										if($captchenable){?>
											<span class="label">
												<label for="wk_mp_captcha"><span id="wk_mp_captchalable1"><?php echo rand(1,20)?></span> + <span id="wk_mp_captchalable2"><?php echo rand(1,20)?></span> =</label>
											</span>
											<input type="text" class="rquired-entry form-control" name="wk_mp_captcha" id="wk_mp_captcha" />
										<?php
										}?>
									</div>
									<div class="modal_footer">
										<span class="error"></span>
										<span class="errormail"></span>
										<input type="reset" value="<?php echo $helper->__('Reset') ?>" id="resetbtn" class="wk_btn wk_btn_default"/>
										<input type="button" value="<?php echo $helper->__('Ask') ?>" id="askbtn" class="wk_btn wk_btn_primary clickask"/>
										<span class="wk_clear"></span>
									</div>
								</form>
							</div>
						</li>      
						<?php
						if($partner->getfacebookid()!=''){
						?>
							<li>
								<span class="icon_social"> <img src="<?php echo $this->getSkinUrl('marketplace/images/icon_fb.png') ?>"></span>
								<a target="_blank" href="https://www.facebook.com/<?php echo $partner->getfacebookid()?>">
									<?php echo $helper->__('Find us on Facebook') ?>
								</a>
							</li>
						<?php
						}
						if($partner->gettwitterid()!=''){
						?>
						<li>
							<span class="icon_social"> <img src="<?php echo $this->getSkinUrl('marketplace/images/icon_instagram.png') ?>" alt=""></span>
							<a target="_blank" href="https://www.instagram.com/<?php echo $partner->gettwitterid() ?>">
								<?php echo $helper->__('Follow us on Instagram') ?>
							</a>		
						</li>
						<?php } ?>
					</ul>	
				</div>

                <!-- Add Favourite -->
                <div>

                    <!--<a class="defaultbutton favourite" href="#" onclick="document.forms.faveform.submit(); return false;">Favourite This Retailer</a>-->

                    <?php

                        $sessionCustomer = Mage::getSingleton('customer/session');
                        if($sessionCustomer->isLoggedIn()) {
                            ?>
                            <form name="faveform" action="" method="post" class="left_form">
                                <input type="hidden" name="favevendor" value="<?php echo $userid ?>">
                                <input type="submit" id="submit" name="submit" value="Favourite This Retailer" class="favourite-submit">
                            </form>
                            <?php  $_POST['favevendor'] = (string)$_POST['favevendor'];
                            $sessionCustomer->getCustomer();
                            $customerData = Mage::getModel('customer/customer')->load($sessionCustomer->getId());
                            $favourite = $customerData->getFavourite();
                            $arrays =  explode(',', $favourite);
                            if (in_array($userid, $arrays)) {
                                ?>
                                <script type="text/javascript">
                                    jQuery(document).ready(function () {
                                        jQuery('#submit').attr('disabled', 'disabled');
                                        jQuery('#submit').addClass('inactivebutton');
                                    });
                                </script>
                             <?php } ?>

                            <?php
                            if (isset($_POST['submit'])) {
                            ?>

                            <?php
                                if (empty($favourite)) {
                                    $customerData->setFavourite($_POST['favevendor']);
                                    $customerData->save();
                                } else {
                                    if (!in_array($userid, $arrays)) {
                                        $favourite2 = $favourite . ',' . $_POST['favevendor'];
                                        $customerData->setFavourite($favourite2);
                                        $customerData->save();
                                    }
                                }

//                                foreach($arrays as $arr) {
//                                    $favourite2 = $arr . ',' . $_POST['favevendor'];
//                                    var_dump($favourite2);
//                                    if (empty($arr)) {
//                                        $customerData->setFavourite($_POST['favevendor']);
//                                        $customerData->save();
//                                    } else {
//                                        if($arr != $userid) {
//                                            $customerData->setFavourite($favourite2);
//                                            $customerData->save();
//                                        }
//                                    }
//                                }
                             $favourite = $customerData->getFavourite();
                             $arrays =  explode(',', $favourite);
                            // check exist favourite retailer
                            if (in_array($userid, $arrays)) {
                            ?>

                            <script type="text/javascript">
                                jQuery(document).ready(function () {
                                    jQuery('#submit').attr('disabled', 'disabled');
                                    jQuery('#submit').addClass('inactivebutton');
                                });
                            </script>

                        <?php
                        }else{
                        ?>
                            <script type="text/javascript">
                                jQuery(document).ready(function () {
                                    jQuery('#submit').attr('enabled', 'enabled');
                                });
                            </script>

                        <?php
                        }

                            }
                        }else{
                            ?>
                            <a href="<?php echo Mage::getUrl('customer/account/login'); ?>" class="login-favourite">Log in to favorite this retailer</a>
                            <?php
                        }

                    ?>
                    <!--<div class="wk_profile_links" style="width:40%; text-align: center">
                        <a class="btn_primary" id="cprofile" href="<?php /*echo rtrim($this->getUrl('seller_detail?seller='.$partner['profileurl']),'/'); */?>"><?php /*echo $helper->__('View Full Collection') */?></a>
                    </div>-->
                </div>

                <!-- End Favourite -->
			</div>
		</div>
	</div>
 </div>

<script>
	$wk_jq=jQuery.noConflict(); 
	(function($wk_jq){
		$wk_jq(function(){			
			$wk_jq('#ask_form').delegate('input,textarea','focus',function(){
				$wk_jq(this).removeClass('error_border');
			});
			$wk_jq('.wrapper').append($wk_jq('#ask_data'));
			$wk_jq('.ask_que').click(function(){
				$wk_jq('#ask_form input,#ask_form textarea').removeClass('error_border');
				$wk_jq('.page').css('opacity','0.4');
				$wk_jq('#ask_data').show();
			});
			$wk_jq('.wk_close').click(function(){
				$wk_jq('.page').css('opacity','1');
				$wk_jq('#resetbtn').trigger('click');
				$wk_jq('#ask_data').hide();
			});
			
			$wk_jq('#askbtn').click(function(){
				var thisthis = $wk_jq(this);
				if(thisthis.hasClass("clickask")){					
					if(!validateEmail($wk_jq('.queryemail').val())){
						$wk_jq(this).addClass('error_border');
						$wk_jq('#ask_form .errormail').text("<?php echo $helper->__(' Enter valid email Id ') ?>").slideDown('slow').delay(2000).slideUp('slow');
					}else{
						var f=0;
						$wk_jq('#ask_form input,#ask_form textarea').each(function(){
							if($wk_jq(this).val()==''){
								$wk_jq(this).addClass('error_border');
								f++;
							}
						});
						if(f>0){
							$wk_jq('#ask_form .error').text("<?php echo $helper->__(' Fill all the fields ') ?>").slideDown('slow').delay(2000).slideUp('slow');
						}else{
							<?php 
							if($captchenable){?>
								var total = parseInt($wk_jq('#wk_mp_captchalable1').text()) + parseInt($wk_jq('#wk_mp_captchalable2').text());
								var wk_mp_captcha = $wk_jq('#wk_mp_captcha').val();
								if(total != wk_mp_captcha){
									$wk_jq('#wk_mp_captchalable1').text(Math.floor((Math.random()*10)+1));
									$wk_jq('#wk_mp_captchalable2').text(Math.floor((Math.random()*100)+1));
									$wk_jq('#wk_mp_captcha').val('');
									$wk_jq('#wk_mp_captcha').addClass('error_border');
									$wk_jq(this).addClass('error_border');
									$wk_jq('#ask_form .errormail').text("<?php echo $helper->__(' Wrong varification number. ') ?>").slideDown('slow').delay(2000).slideUp('slow');
								}else{
									thisthis.removeClass('clickask');
									$wk_jq('#ask_data').addClass('mail_procss');
									$wk_jq.ajax({
										url:'<?php echo Mage::getBaseUrl();?>marketplace/seller/sendmail',
										data:$wk_jq('#ask_form').serialize(),
										type:'post',
										dataType:'json',
										success:function(d){
											thisthis.addClass('clickask');
											$wk_jq('#ask_data').removeClass('mail_procss')
											alert("<?php echo $helper->__(' Mail Send ') ?>..");
											$wk_jq('.wk_close,#resetbtn').trigger('click');
										}
									});
								}
							<?php 
							}else{?>
								thisthis.removeClass('clickask');
									$wk_jq('#ask_data').addClass('mail_procss');
									$wk_jq.ajax({
										url:'<?php echo Mage::getBaseUrl();?>marketplace/seller/sendmail',
										data:$wk_jq('#ask_form').serialize(),
										type:'post',
										dataType:'json',
										success:function(d){
											thisthis.addClass('clickask');
											$wk_jq('#ask_data').removeClass('mail_procss');
											alert("<?php echo $helper->__(' Mail Send ') ?>..");
											$wk_jq('.wk_close,#resetbtn').trigger('click');
										}
									});
								<?php 
							}?>
						}	
					}
				}
			});
		});
	})($wk_jq);
	function validateEmail($email) {
	  var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
	  if( !emailReg.test( $email ) ) {
		return false;
	  } else {
		return true;
	  }
	}
</script>