<?php
$feeds=$this->getFeed();
$temp=explode('/profile/',Mage::helper('core/url')->getCurrentUrl());
$helper =Mage::helper('marketplace');
if($temp[1]!=''){
	$partner=$this->getProfileDetail();
	?>	
	<style>
	.main{background-image:none;background-color:<?php echo $partner->getbackgroundth();?>;}
	.mpfeedback span {
	font-size: 1.1em;
	}</style>
	<div class="wk_mp_design">
		<div class="block block-account">	
			<div class="block-title">	
				<strong><span><h4></h4></span></strong>
			</div>
		</div>
		<div class="fieldset wk_mp_fieldset">
			<div class="wk_mp_detail">
<!--				<div class="row">			-->
<!--					<h4 class="label wk_txt_trans">--><?php //echo $helper->__('About');?><!--</h4>-->
<!--					<span class="data">--><?php //echo $partner->getcompdesi();?><!--</span>		-->
<!--				</div>-->
				<div class="row">			
					<h4 class="label wk_txt_trans"><?php echo $helper->__('Detailed Rating');?></h4>
					<span class="data">
						<div class="mpfeedback">
							<div class="price">
								<span class="wk_ordertitle_label wk_span" style="width:10%"><?php echo $helper->__('Price') ?> </span><span class="wk_ordertitle_label">:</span>
								<div class="ratingslider-box">
									<div class="rating" style="width:<?php echo ceil($feeds['price']);?>%;"></div>
								</div>
								<span>&nbsp;&nbsp;&nbsp;(<?php echo $feeds['feedcount']?>)</span>
								<div class="clear"></div>
							</div>
							<div class="value">
								<span class="wk_ordertitle_label wk_span" style="width:10%"><?php echo $helper->__('Value') ?> </span><span class="wk_ordertitle_label">:</span>
								<div class="ratingslider-box" >
									<div class="rating" style="width:<?php echo ceil($feeds['value']);?>%;"></div>								
								</div>
								<span>&nbsp;&nbsp;&nbsp;(<?php echo $feeds['feedcount']?>)</span>
								<div class="clear"></div>
							</div>
							<div class="quality">
								<span class="wk_ordertitle_label wk_span" style="width:10%"><?php echo $helper->__('Quality') ?> </span><span class="wk_ordertitle_label">:</span>
								<div class="ratingslider-box">
									<div class="rating" style="width:<?php echo ceil($feeds['quality']);?>%;"></div>
								</div>
								<span>&nbsp;&nbsp;&nbsp;(<?php echo $feeds['feedcount']?>)</span>
								<div class="wk_clear"></div>
							</div>
						</div>
					</span>		
				</div>
				<div class="row">
					<div class="wk_mp_design" style="padding-top: 10px;" id="return-policy">
						<div class="block block-account">
							<div class="block-title">
								<strong><span><h4><?php echo $helper->__("Exchange / Refund Policy") ?></h4></span></strong>
							</div>
						</div>
						<div class="fieldset wk_mp_fieldset">
							<div class="wk_mp_detail">
								<div class="row nicEdit-main">
									<span class="data"><?php echo $partner->getReturnpolicy();?></span>
								</div>
							</div>

						</div>
					</div>
				</div>


			</div>
		</div>
	 </div> 	
<?php
}?>