<div class="bso-index">
    <div style="text-align:center;">
        <img src="<?php echo $this->getSkinUrl('images/xcareer_title_2.jpg') ?>" style="width:100%; max-width:500px;margin-top:10px;" alt="top" pagespeed_url_hash="4126934999" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></div>
    <div id="whysell" style="margin:0 auto;max-width:650px;padding-left:10px;padding-right:10px;">
        <ol>
            <h2>1. Business Development</h2>
            <li style="padding-bottom:20px;padding-top:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;text-decoration:underline;">Job Highlights</span><ol>
                    <li>- Results driven</li>
                    <li>- Excellent communication and negotiation skills</li>
                    <li>- Min 2 years B2B Business Development experience</li></ol></li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;text-decoration:underline;">Job Description</span>Our team is in the search of a highly motivated Business Development professional to grow the company's B2B initiatives. Responsible for identifying and acquiring new customers through regular prospecting or leads, the successful candidate will play an integral role in meeting the long-term business goals in line with the company's vision and mission. This new member of the team is also expected to build and maintain strong relationships with existing and new customers to achieve sustainable business targets.</li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;text-decoration:underline;">Key Responsibilities</span><ol>
                    <li> - Build the company's reputation across various industries and markets</li><li>- Acquire new accounts and build long term partnerships </li>
                    <li>- Effectively identify client requirements and provide useful solutions</li>
                    <li>- Actively participate in the company's strategy and product development process</li>
                    <li>- Remain current with news on competitors, industry, and market trends</li>
                    <li>- Maintain relevancy by attending workshops, reviewing professional publications, establishing professional networks, and benchmarking best practices</li>
                    <li>- Build a sustainable pipeline and ensure that quotas and targets are met and exceeded</li>
                    <li>- Prepare written presentations, reports and quotations</li>
                    <li>- Conduct satisfaction checks and solicit referrals</li>
                    <li>- Perform other tasks separately assigned in addition to the above</li>
                </ol>
            </li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;text-decoration:underline;">Requirements</span><ol>
                    <li> - Diploma in Computer Science / IT / Business or equivalent with at least 2 years of B2B Business Development experience</li><li>- Excellent communicator with strong technical understanding of enterprise software, web, mobile products and other IT solutions</li>
                    <li>- Effective presentation and client relationship skills with an emphasis on excellent customer experience</li>
                    <li>- Ability to engage with key decision makers</li>
                    <li>- Independent, motivated, and aggressive in developing new businesses with an established track record</li>
                    <li>- Strong business acumen</li>
                    <li>- Excellent presentation, communication, and negotiation skills</li>
                    <li>- Fluency in written and spoken English is mandatory</li>
                    <li>- Process-oriented, and customer-focused team player</li>
                </ol></li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;text-decoration:underline;">How to Apply?</span> If you are interested to be part of the team, please send us your cover letter and updated resume, stating current and expected salaries to <a href="mailto:careers@bugisstreet.com.sg">careers@bugisstreet.com.sg</a> with the Subject "Application for Bugis Street Online Business Development"
                We regret that only shortlisted candidates will be notified.</li>
        </ol>
    </div>

</div>