<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ui.js') ?>"></script>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/style-m.css') ?>">

<div id="faq" class="content">

    <div id="faq-header" class="page-title">

        <h1>FAQ</h1>

        <div id="faq-help">

            Need Help? <a href="<?php echo $this->getUrl('contacts/') ?>" title="Contact Us">Contact Us</a>

        </div><div class="clear"></div>

    </div>

    <div id="faq-sections">

        <ul>

            <li><span class="myaccount anchor" href="#myaccount"></span><a href="#myaccount" title="My Account" class="anchor">My Account</a></li>

            <li><span class="shopping anchor" href="#shopping"></span><a href="#shopping" title="Shopping" class="anchor">Shopping</a></li>

            <li><span class="payment anchor" href="#payment"></span><a href="#payment" title="Payment" class="anchor">Payment &amp; Taxes</a></li>

            <li><span class="shipping_tracking anchor" href="#shipping_tracking"></span><a href="#shipping_tracking" title="Shipping &amp; Tracking" class="anchor">Shipping &amp; Tracking</a></li>

            <li><span class="returns anchor" href="#returns"></span><a href="#returns" title="Returns" class="anchor">Exchange or Refund</a></li>

            <li><span class="giftcards anchor" href="#giftcards"></span><a href="#giftcards" title="Payment" class="giftcards">Store Credits</a></li><!--5mar-->

            <li><span class="seller anchor" href="#seller"></span><a href="#seller" title="seller" class="seller">Selling</a></li>

            <!--5mar-->

        </ul><div class="clear"></div>

    </div>



    <div class="section-header first">

        <a name="myaccount" id="myaccount"></a><span class="myaccount"></span><h3>MY ACCOUNT</h3><h3>

        </h3></div><div class="clear"></div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-0" aria-controls="ui-accordion-1-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How can I create my own account?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-0" aria-labelledby="ui-accordion-1-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Just click <a href="http://www.bugisstreet.com.sg/index.php/customer/account/create/" target="_blank">here</a>. It's easy, and it's FREE!</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-1" aria-controls="ui-accordion-1-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Do I need an account to start shopping?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-1" aria-labelledby="ui-accordion-1-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Nope, but having an account makes things much easier, so you can just focus on the shopping.</p>

            <p>Registered shoppers will be able to track orders, review past orders, create a want list, bookmark favorite shops, and access all the other features of the Bugis Street Online Store account!</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-2" aria-controls="ui-accordion-1-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Is my personal information kept private?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-2" aria-labelledby="ui-accordion-1-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Definitely. We'll keep all your details private and confidential, away from third parties. Feel free to read our Privacy Policy <a href="http://www.bugisstreet.com.sg/privacy-policy/">here</a>.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-2" aria-controls="ui-accordion-1-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How do I get to know of the latest discounts or promotions?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-2" aria-labelledby="ui-accordion-1-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Subscribe to our newsletter	and you will be the first to get the inside scoop!</p>

        </div>

    </div>



    <div class="section-header">

        <a name="shopping" id="shopping"></a><span class="shopping"></span><h3>SHOPPING</h3><h3>

        </h3></div><div class="clear"></div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-0" aria-controls="ui-accordion-2-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How do I start shopping?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-0" aria-labelledby="ui-accordion-2-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Whenever the shopping bug strikes, log on to <a href="http://www.bugisstreet.com.sg" target="_blank">www.BugisStreet.com.sg</a> (It works on your mobile device too!) to browse, add to cart, and checkout!</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-1" aria-controls="ui-accordion-2-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What currency are the prices displayed in?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-1" aria-labelledby="ui-accordion-2-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>All prices are in Singapore Dollars (SGD) by default, and are inclusive of taxes, if applicable. You can choose to change the displayed currency anytime from the top right hand corner of the page.</p>



            <p>The site is capable of displaying prices in 9 different currencies, including Singapore Dollar, Malaysian Ringgit, US Dollar, Australian Dollar, Japanese Yen, Thai Baht, Chinese Yuan, Brunei Dollar, and Vietnamese Dong. Exchange rates are for reference only and are based on market conditions, updated <a href="http://www.dbs.com/ratesonline/Pages/fxbra.aspx" target="_blank">here</a>. Do take note that all transactions will be in Singapore Dollars.</p>

        </div>
       
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-3" aria-controls="ui-accordion-2-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I changed my mind. Can I amend/cancel my order?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-3" aria-labelledby="ui-accordion-2-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Once a transaction is complete and the order is confirmed, we are unable to modify or cancel it.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-4" aria-controls="ui-accordion-2-panel-4" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I received an incorrect/defective item. What do I do now?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-4" aria-labelledby="ui-accordion-2-header-4" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Please refer to the Exchange or Refund section for more information on how to make things right.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-5" aria-controls="ui-accordion-2-panel-5" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I did not receive my item. What do I do now?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-5" aria-labelledby="ui-accordion-2-header-5" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>You may contact the Seller directly to check on your item. The Seller's contact information can be found on the Seller's profile page.</p>

        </div>

    </div>



    <div class="section-header">

        <a name="payment" id="payment"></a><span class="payment"></span>

        <h3>PAYMENT &amp; TAXES</h3><h3>

        </h3></div>

    <div class="clear"></div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-0" aria-controls="ui-accordion-3-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What forms of payment do you accept?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-0" aria-labelledby="ui-accordion-3-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>We accept direct debit with eNETS and major credit/debit cards, including Visa and MasterCard.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-1" aria-controls="ui-accordion-3-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Do you accept international credit cards?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-1" aria-labelledby="ui-accordion-3-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Yes. Do note that international bank transaction fees and foreign exchange rates will apply.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-2" aria-controls="ui-accordion-3-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Is it safe to use my credit card in your site?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-2" aria-labelledby="ui-accordion-3-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Of course! To ensure that all online transactions on our site are safe and secure, we've partnered with Telemoney, an international electronics payments provider, and NETS.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-3" aria-controls="ui-accordion-3-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>My computer froze while processing the payment, how do I know if my payment went through successfully?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-3" aria-labelledby="ui-accordion-3-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>If your payment was successful, you should be redirected to a thank you page and a confirmation email will be sent to you.</p>

            <p>When in doubt, do contact your bank to check if a transaction has been made.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-4" aria-controls="ui-accordion-3-panel-4" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I'm located abroad, how do I pay for the taxes of my purchases?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-4" aria-labelledby="ui-accordion-3-header-4" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Additional import duties, customs and local sales taxes may be levied on overseas purchases and these will be the responsibility of the shopper.</p>

        </div>

    </div>





    <div class="section-header">

        <a name="shipping_tracking" id="shipping_tracking"></a><span class="shipping_tracking"></span><h3>SHIPPING AND TRACKING</h3><h3>

        </h3></div><div class="clear"></div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
	
    <div class="ui-helper-reset ui-widget-content ui-corner-bottom" style="color:#333333;font-size:0.8em;outline:none;padding-left: 78px;">
	<p>Registered mail is recommended, because you will be able to track your item/s, whenever possible.</p>
	<p>Please note that Bugis Street Online Pte. Ltd. will not be held responsible for any loss of mail packages, regardless of which shipping method was selected.</p>
    </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-0" aria-controls="ui-accordion-4-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What are the shipping charges?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-0" aria-labelledby="ui-accordion-4-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>The shipping methods and their respective charges offered by the Seller will be displayed as options on the checkout page. You can verify the total amount before you proceed with payment at checkout.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-1" aria-controls="ui-accordion-4-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How long does it take for me to receive my packages?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-1" aria-labelledby="ui-accordion-4-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Local shipping will usually take 5-7 business days. International shipping will usually take 7-14 business days.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-2" aria-controls="ui-accordion-4-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Can you ship to two different locations?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-2" aria-labelledby="ui-accordion-4-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Unfortunately, we are not able to cater to such an arrangement. We can only ship each order to a single address. To get your items delivered to separate addresses, please make another order.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-3" aria-controls="ui-accordion-4-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>It's been a while and my items have yet to arrive, what should I do?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-3" aria-labelledby="ui-accordion-4-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>You may log in to your account to view the status of your order. Otherwise, please contact the Seller directly. </p>

        </div>

    </div>







    <div class="section-header">

        <a name="returns" id="returns"></a>

        <span class="returns"></span><h3>EXCHANGE OR REFUND</h3><h3>

        </h3></div>

    <div class="clear"></div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-1" aria-controls="ui-accordion-5-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How can I request for an exchange for my incorrect/defective item?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-1" aria-labelledby="ui-accordion-5-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>If you checked out with your Bugis Street Online Store account, you may log in to your account, and submit an exchange request under My Orders. Select the associated order number and request RMA.</p>

            <p>The Seller will evaluate your request to ensure that it is valid. This should take between 3–5 business days. Upon approval, you will be contacted with further instructions.</p>
            
            <p>However, if you checked out as a Guest, please contact the Seller directly. The Seller’s contact information can be found on the Seller’s profile page.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-3" aria-controls="ui-accordion-5-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Can I get a refund instead of an exchange?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-3" aria-labelledby="ui-accordion-5-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Exchange or Refund policies vary from Seller to Seller. Please refer to the respective Seller’s profile page for their return policies. You are encouraged to view and understand the Exchange or Refund policies before making your purchase.</p>

        </div>

    </div>



    <div class="section-header">

        <a name="giftcards" id="giftcards"></a>

        <span class="giftcards"></span><h3>STORE CREDITS</h3></div>

    <div class="clear"></div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
	
            <div class="ui-helper-reset ui-widget-content ui-corner-bottom" style="color:#333333;font-size:0.8em;outline:none;">
            
	<p style="padding-left: 78px;">Please note that Bugis Street Online store credits are<br>
		- valid for 1 month;<br>
		- for one-time use only; i.e. It must be redeemed within a single transaction;<br>
		- strictly non-refundable, non-extendable, and not exchangeable for cash.
	</p>
    </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-6-header-0" aria-controls="ui-accordion-6-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I received a refund in the form of a store credits. How do I use it?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-6-panel-0" aria-labelledby="ui-accordion-6-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>You may enter the store credit code during checkout to offset any purchase you are making on the Bugis Street Online Store.</p>

        </div>

    </div>



    <div class="section-header">

        <a name="seller" id="seller"></a>

        <span class="seller"></span>

        <h3>SELLING</h3>

        <h3>

        </h3></div>

    <div class="clear"></div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-0" aria-controls="ui-accordion-5-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What can I sell?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-0" aria-labelledby="ui-accordion-5-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>The Bugis Street Online Store is a marketplace for anybody looking to start or grow an online business. If the item that you want to sell does not belong to any of the available categories, please <a href="http://www.bugisstreet.com.sg/contacts/">Contact Us</a> and hang in there. We can always add new categories to make the store even more exciting.</p>

        </div>

		<h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-1" aria-controls="ui-accordion-5-panel-1" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What can't be sold on the Bugis Street Online Store?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-1" aria-labelledby="ui-accordion-5-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>
				<ol>
  				<li type="a">Products that contain misleading advertising or false claims, whether on the Product label itself, in the Product description page on the Electronic Marketplace Platform or otherwise;</li>
  				<li type="a">Products that infringe third-party rights, including property rights and intellectual property rights;</li>
  				<li type="a">Products that are obscene or vulgar;</li>
				<li type="a">Industrial Products which have failed to pass inspection/examination;</li>
				<li type="a">Illegal copies of videos, music or games;</li>
				<li type="a">Stolen or lost Products;</li>
				<li type="a">Products which Singapore Customs classifies as "prohibited goods" or "controlled goods"; or</li>
				<li type="a">Any goods for which an on-line transaction to offer to sell, sell and/or purchase such goods is prohibited under applicable laws and regulations.</li>
				</ol>
			</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-2" aria-controls="ui-accordion-5-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What are the sign up fees, subscription fees &amp; listing fees?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-2" aria-labelledby="ui-accordion-5-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>The Bugis Street Online Store does not charge any sign up fees, subscription fees, nor listing fees.</p>



        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-3" aria-controls="ui-accordion-5-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Do you take a percentage of each sale?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-3" aria-labelledby="ui-accordion-5-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Since it is free to list your item, you only pay when you make a sale! Whenever you make a sale on the Bugis Street Online Store, we take a 13% commission on your sales. Payment gateway charges are applicable as well.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-4" aria-controls="ui-accordion-5-panel-4" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How would I know if someone confirms a purchase online?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-4" aria-labelledby="ui-accordion-5-header-4" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Whenever somebody buys something from your online store, you will receive a notification via email immediately. Don't forget to check that our emails don't end up in your junk folder!</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-5" aria-controls="ui-accordion-5-panel-5" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How do I get paid?</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-5" aria-labelledby="ui-accordion-5-header-5" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Buyers pay for purchases with their credit/debit card, or eNETS direct debit in Singapore dollars, and your earnings will be credited to your bank account within 30 days of the transaction in Singapore dollars as well.</p>

        </div>

        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-6" aria-controls="ui-accordion-5-panel-6" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I have more questions.</h3>

        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-6" aria-labelledby="ui-accordion-5-header-6" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">

            <p>Do not hesitate to <a href="http://www.bugisstreet.com.sg/contacts/" target="_blank">contact us</a>. We are here to help.</p>

        </div>

    </div>



</div>

<script>

    var header_h = jQuery(".topnav-wrapper").height() + 0;

    var changepoint = parseInt(header_h  * 2);

    function header_transform() {

        window_y = jQuery(window).scrollTop();

        if(window_y > changepoint) {

            jQuery('.backtotop').show();

        } else {

            jQuery('.backtotop').hide();

        }

    }



    jQuery(function() {

        jQuery( ".accordion" ).accordion({heightStyle: "content",collapsible: true, active: false,header: "h3"});

        jQuery('.anchor').click(function(){

            var sto = jQuery(this).attr("href");

            jQuery('html, body').animate({scrollTop:jQuery(sto).position().top}, 'slow');

            return false;

        });



        jQuery('.backtotop').click(function(){

            jQuery('html, body').animate({scrollTop:0}, 'slow');

            return false;

        });



        jQuery(window).scroll(function() {

            header_transform();

        });

    });

</script>