<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ui.js') ?>"></script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/style-m.css') ?>">
<div id="faq" class="content">
    <div id="faq-header" class="page-title">
        <h1>FAQ</h1>
        <div id="faq-help">
            Need Help? <a href="<?php echo $this->getUrl('contacts/') ?>" title="Contact Us">Contact Us</a>
        </div><div class="clear"></div>
    </div>
    <div id="faq-sections">
        <ul>
            <li><span class="myaccount anchor" href="#myaccount"></span><a href="#myaccount" title="My Account" class="anchor">My Account</a></li>
            <li><span class="shopping anchor" href="#shopping"></span><a href="#shopping" title="Shopping" class="anchor">Shopping</a></li>
            <li><span class="payment anchor" href="#payment"></span><a href="#payment" title="Payment" class="anchor">Payment &amp; Taxes</a></li>
            <li><span class="shipping_tracking anchor" href="#shipping_tracking"></span><a href="#shipping_tracking" title="Shipping &amp; Tracking" class="anchor">Shipping &amp; Tracking</a></li>
            <li><span class="returns anchor" href="#returns"></span><a href="#returns" title="Returns" class="anchor">Returns &amp; Exchanges</a></li>
            <li><span class="giftcards anchor" href="#giftcards"></span><a href="#giftcards" title="Payment" class="giftcards">Coupon Codes</a></li><!--5mar-->
            <li><span class="seller anchor" href="#seller"></span><a href="#seller" title="seller" class="seller">Selling</a></li>
            <!--5mar-->
        </ul><div class="clear"></div>
    </div>

    <div class="section-header first">
        <a name="myaccount" id="myaccount"></a><span class="myaccount"></span><h3>MY ACCOUNT</h3><h3>
        </h3></div><div class="clear"></div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-0" aria-controls="ui-accordion-1-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How can I create my own account?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-0" aria-labelledby="ui-accordion-1-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Just click <a href="http://www.bugisstreet.com.sg/index.php/customer/account/create/" target="_blank">here</a>. It's free and easy!</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-1" aria-controls="ui-accordion-1-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Do I need an account to start shopping?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-1" aria-labelledby="ui-accordion-1-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Nope, but having an account makes things much easier, so you can just focus on the shopping.</p>
            <p>Registered shoppers will be able to track orders, review past orders, request to return items, create want lists, bookmark favorite shops, and more!</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-2" aria-controls="ui-accordion-1-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Is my personal information kept private?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-2" aria-labelledby="ui-accordion-1-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Definitely. We'll keep all your details private and confidential, away from third parties. Feel free to read our Privacy Policy <a href="http://www.bugisstreet.com.sg/index.php/privacy_policy/" target="_blank">here</a>.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-2" aria-controls="ui-accordion-1-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How do I get to know of the latest discounts or promotions?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-1-panel-2" aria-labelledby="ui-accordion-1-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Subscribe to our newsletter	and you will be the first to get the inside scoop!</p>
        </div>
    </div>

    <div class="section-header">
        <a name="shopping" id="shopping"></a><span class="shopping"></span><h3>SHOPPING</h3><h3>
        </h3></div><div class="clear"></div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-0" aria-controls="ui-accordion-2-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How do I start shopping?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-0" aria-labelledby="ui-accordion-2-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Whenever the shopping bug strikes, log on to <a href="http://www.bugisstreet.com.sg" target="_blank">www.BugisStreet.com.sg</a> (works on your mobile device too!) to browse, add to cart, and checkout!</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-1" aria-controls="ui-accordion-2-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What currency are the prices displayed in?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-1" aria-labelledby="ui-accordion-2-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>All prices are in Singapore Dollars (SGD) by default, and are inclusive of taxes, if applicable. You can choose to change the displayed currency anytime from the top right hand corner of the page.</p>

            <p>The site is capable of displaying prices in 9 different currencies, including Singapore Dollar, Malaysian Ringgit, US Dollar, Australian Dollar, Japanese Yen, Thai Baht, Chinese Yuan, Brunei Dollar, and Vietnamese Dong. Exchange rates are for reference only and are based on market conditions, updated <a href="http://www.dbs.com/ratesonline/Pages/fxbra.aspx" target="_blank">here</a>. Do take note that all transactions will be in Singapore Dollars.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-2" aria-controls="ui-accordion-2-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How do I know what size to buy?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-2" aria-labelledby="ui-accordion-2-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>When in doubt, just click on the Size Guide link on the product page and grab a dressmaker's tape to determine the right size based on the measuring guide.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-3" aria-controls="ui-accordion-2-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I changed my mind. Can I amend/cancel my order?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-3" aria-labelledby="ui-accordion-2-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Once a transaction is complete and the order is confirmed, we are unable to modify or cancel it.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-4" aria-controls="ui-accordion-2-panel-4" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I received an incorrect/defective item. What do I do now?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-4" aria-labelledby="ui-accordion-2-header-4" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Please let us know by submitting a returns request <a href="http://www.bugisstreet.com.sg/index.php/awrma/guest_rma/index/" target="_blank">here</a>, so we can do our best to make things right. </p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-2-header-5" aria-controls="ui-accordion-2-panel-5" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I did not receive my item. What do I do now?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-2-panel-5" aria-labelledby="ui-accordion-2-header-5" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Please drop us a note <a href="http://bugisstreet.com.sg/index.php/webforms/index/index/id/2/" target="_blank">here</a> to inform us about the missing item and we will track it down for you as soon as possible. </p>
        </div>
    </div>

    <div class="section-header">
        <a name="payment" id="payment"></a><span class="payment"></span>
        <h3>PAYMENT &amp; TAXES</h3><h3>
        </h3></div>
    <div class="clear"></div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-0" aria-controls="ui-accordion-3-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What forms of payment do you accept?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-0" aria-labelledby="ui-accordion-3-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>We accept direct debit with eNETS and major credit and debit cards, including Visa and MasterCard.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-1" aria-controls="ui-accordion-3-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Do you accept international credit cards?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-1" aria-labelledby="ui-accordion-3-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Yes. Do note that international bank transaction fees and foreign exchange rates will apply.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-2" aria-controls="ui-accordion-3-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Is it safe to use my credit card in your site?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-2" aria-labelledby="ui-accordion-3-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Of course! To ensure that all online transactions on our site are safe and secure, we've partnered with Wirecard, an international electronics payments provider, and NETS.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-3" aria-controls="ui-accordion-3-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>My computer froze while processing the payment, how do I know if my payment went through successfully?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-3" aria-labelledby="ui-accordion-3-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>If your payment was successful, you should be redirected to a thank you page and a confirmation email will be sent to you.</p>
            <p>When in doubt, do contact your bank to check if a transaction has been made.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-3-header-4" aria-controls="ui-accordion-3-panel-4" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I'm located abroad, how do I pay for the taxes of my purchases?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-4" aria-labelledby="ui-accordion-3-header-4" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Additional import duties, customs and local sales taxes may be levied on overseas purchases and these will be the responsibility of the shopper.</p>
        </div>
    </div>


    <div class="section-header">
        <a name="shipping_tracking" id="shipping_tracking"></a><span class="shipping_tracking"></span><h3>SHIPPING AND TRACKING</h3><h3>
        </h3></div><div class="clear"></div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-0" aria-controls="ui-accordion-4-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What are the shipping charges?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-0" aria-labelledby="ui-accordion-4-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>The shipping methods and their respective charges offered by the Seller will be displayed as options on the checkout page. You can verify the total amount before you proceed with payment at checkout.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-1" aria-controls="ui-accordion-4-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How long does it take for me to receive my packages?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-1" aria-labelledby="ui-accordion-4-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Local shipping will usually take 5-7 business days. International shipping will usually take 7-14 business days.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-2" aria-controls="ui-accordion-4-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Can you ship to two different locations?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-2" aria-labelledby="ui-accordion-4-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Unfortunately, no. We can only ship each order to a single address. To get your items delivered to separate addresses, please split the order.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-4-header-3" aria-controls="ui-accordion-4-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>It's been a while and my items have yet to arrive, what should I do?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-4-panel-3" aria-labelledby="ui-accordion-4-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Please drop us a note <a href="http://bugisstreet.com.sg/index.php/webforms/index/index/id/2/" target="_blank">here</a> to inform us about the missing item and we will track it down for you as soon as possible.</p>
        </div>
    </div>



    <div class="section-header">
        <a name="returns" id="returns"></a>
        <span class="returns"></span><h3>RETURNS &amp; EXCHANGES</h3><h3>
        </h3></div>
    <div class="clear"></div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-0" aria-controls="ui-accordion-5-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Can I return an item?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-0" aria-labelledby="ui-accordion-5-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>We accept returns for items that are defective, damaged during delivery, or wrongly delivered.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-1" aria-controls="ui-accordion-5-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How can I return an item?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-1" aria-labelledby="ui-accordion-5-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>To return an item, first submit a returns request form <a href="http://www.bugisstreet.com.sg/index.php/awrma/guest_rma/index/" target="_blank">here</a>.</p>
            <p>The seller will evaluate your request to ensure that it is valid. This should take between 3–5 business days. Upon approval, you will be contacted with further instructions.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-2" aria-controls="ui-accordion-5-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What happens after my returns request is approved?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-2" aria-labelledby="ui-accordion-5-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Once your returns request is approved, you will be given an RMA (Returns Merchandise Authorisation) number, along with instructions to mail the item back to the seller within 14 business days.</p>

            <p>Once the seller has received your item, the exchange wil be processed. However, if the item is not available for exchange, the purchase amount will be refunded to you in the form of store credit or via the same payment method that was used for the original purchase.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-3" aria-controls="ui-accordion-5-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Can I get a refund instead of an exchange?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-3" aria-labelledby="ui-accordion-5-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Sellers only offer refunds when the item is not available for an exchange.</p>
        </div>
    </div>

    <div class="section-header">
        <a name="giftcards" id="giftcards"></a>
        <span class="giftcards"></span><h3>COUPON CODES</h3><h3><!--5mar-->
        </h3></div>
    <div class="clear"></div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-6-header-0" aria-controls="ui-accordion-6-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I received a refund in the form of a store credit coupon code. How do I use it?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-6-panel-0" aria-labelledby="ui-accordion-6-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>You may enter the coupon code during checkout to offset any purchase you are making on the Bugis Street Online Store.</p>

            <p>Do note that the coupon code is valid for one-time use only i.e. it cannot be split up for multiple orders.</p>
        </div>
    </div>

    <div class="section-header">
        <a name="seller" id="seller"></a>
        <span class="seller"></span>
        <h3>SELLING</h3>
        <h3>
        </h3></div>
    <div class="clear"></div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-0" aria-controls="ui-accordion-5-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What can I sell?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-0" aria-labelledby="ui-accordion-5-header-0" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>The Bugis Street Online Store is a marketplace for anybody looking to start or grow an online business. We currently have 4 main categories, comprising: Women, Men, Electronics, and Gifts. If the item that you want to sell does not belong to any of the available categories, please <a href="http://www.bugisstreet.com.sg/index.php/webforms/index/index/id/2/">Contact Us</a> and hang in there. We can always add new categories to make the store even more exciting. If you wish to learn more about what can't be sold on the Bugis Street Online Store, click <span style="color:#999;">here</span> to read more</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-1" aria-controls="ui-accordion-5-panel-1" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>What are the sign up fees, subscription fees &amp; listing fees?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-1" aria-labelledby="ui-accordion-5-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>The Bugis Street Online Store does not charge any sign up fees, subscription fees, nor listing fees.</p>

        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-2" aria-controls="ui-accordion-5-panel-2" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>Do you take a percentage of each sale?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-2" aria-labelledby="ui-accordion-5-header-2" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Since it is free to list your item, you only pay when you sell! Whenever you make a sale on the Bugis Street Online Store, we take a 13% commission on your sales. Payment gateway charges are applicable as well. Click <span style="color:#999;">here</span> for a more comprehensive explanation of the percentages.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-3" aria-controls="ui-accordion-5-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How would I know if someone confirms a purchase online?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-3" aria-labelledby="ui-accordion-5-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Whenever somebody buys something from your online store, you will receive a notification via email immediately. Don't forget to check that our emails don't end up in your junk folder!</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-3" aria-controls="ui-accordion-5-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>How do I get paid?</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-3" aria-labelledby="ui-accordion-5-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Buyers pay for purchases with their credit/debit card, or eNETS direct debit in Singapore dollars, and you will receive your earnings to your bank account within 30 days of the transaction in Singapore dollars as well.</p>
        </div>
        <h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-5-header-3" aria-controls="ui-accordion-5-panel-3" aria-selected="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>I have more questions.</h3>
        <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-5-panel-3" aria-labelledby="ui-accordion-5-header-3" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
            <p>Do not hesitate to <a href="http://www.bugisstreet.com.sg/index.php/webforms/index/index/id/2/" target="_blank">contact us</a>. We are here to help.</p>
        </div>
    </div>

</div>
<script>
    var header_h = jQuery(".topnav-wrapper").height() + 0;
    var changepoint = parseInt(header_h  * 2);
    function header_transform() {
        window_y = jQuery(window).scrollTop();
        if(window_y > changepoint) {
            jQuery('.backtotop').show();
        } else {
            jQuery('.backtotop').hide();
        }
    }

    jQuery(function() {
        jQuery( ".accordion" ).accordion({heightStyle: "content",collapsible: true, active: false,header: "h3"});
        jQuery('.anchor').click(function(){
            var sto = jQuery(this).attr("href");
            jQuery('html, body').animate({scrollTop:jQuery(sto).position().top}, 'slow');
            return false;
        });

        jQuery('.backtotop').click(function(){
            jQuery('html, body').animate({scrollTop:0}, 'slow');
            return false;
        });

        jQuery(window).scroll(function() {
            header_transform();
        });
    });
</script>