<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/style-m.css') ?>">
<div id="terms" class="content">
    <div class="page-title">
        <h1>PRIVACY POLICY</h1>
        <div class="clear"></div>
    </div>
    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
        <div class="ui-accordion-header ui-helper-reset ui-state-default ui-accordion-icons ui-accordion-header-active ui-state-active ui-corner-top" role="tab" id="ui-accordion-1-header-0" aria-controls="ui-accordion-1-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-s"></span>
            <p>Bugis Street Online Pte. Ltd. (“we”, “us” or “our”) is committed to protecting and respecting your privacy.</p>
            <p>This Privacy Policy together with our <a href="http://bugisstreet.com.sg/index.php/termsof_use/">Terms of Use</a> applies to your use of and access to: (a) our website www.bugisstreet.com.sg (“our Site”); and (b) any of the services, features, data, software and content accessible through the our Site (“Services”). This Privacy Policy is for Singapore and applies to personal data collected, stored, disclosed and/or processed by us in Singapore.</p>
            <p><b>Please read the following carefully to understand our views and practices regarding your personal data and how we will treat it. </b></p>
            <p><b>By visiting or using our Site, you agree to the terms of this Privacy Policy. If you do not agree to any portion of this Privacy Policy or any of our <a href="http://bugisstreet.com.sg/index.php/termsof_use/">Terms of Use</a>, please do not continue using our Site. </b>If you have already provided any personal information to us, please contact us about how you would like us to handle such information.&nbsp;</p>
            <ol>
                <li>
                    <strong>WHAT INFORMATION DO WE COLLECT?</strong>
                    <p><b>Personal Data</b></p>
                    <p>You may give us information about you by filling in forms on our Site or by corresponding with us by phone, e-mail or otherwise. This includes, without limitation, information you provide when you register to use our Site and our Services, use social media functions on our Site, and when you report a problem with our Site or the Services. The information you give us may include your name, address, e-mail address and phone number, personal description and photograph (“Personal Data”). </p>
                    <p>When you provide Personal Data to us, you are giving us permission to use and store that information consistent with this Privacy Policy, subject to the requirements of applicable law.</p>
                    <p><b>Web Tracking Data</b></p>
                    <p>When you visit our Site or use the Services, we and our third party service providers may automatically collect and store log information from you (“Web Tracking Data”). The information collected and stored may include: </p>
                    <ol>
                        <li>information in server logs, including but not limited to Internet protocol (IP) address, and mobile device IP address, Internet service provider (ISP), clickstream data, browser type and language, viewed and exit pages and date or time stamps; your login information, browser type and version, time zone setting, browser plug-in types and versions, operating system and platform;</li>
                        <li>information about your visit, including the full Uniform Resource Locators (URL) clickstream to, through and from our Site (including date and time); information you viewed or searched for; page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page and any phone number used to call our customer service number; and</li>
                        <li>information about the device you use to access our Site or to use the Services, including unique device identifiers, usage information (such as page requests and average time spent on our Site) operating system, browser type and the device’s mobile network information and telephone number (if relevant). </li>
                    </ol>
                </li>

                <li>
                    <strong>USE AND DISCLOSURE OF INFORMATION</strong>
                    <p><b>Personal Data</b></p>
                    <p>We will use and store Personal Data to deliver the Services to you, to carry out our obligations arising from any agreements entered into between you and us and to provide you with such information or Services as you may request from us, to allow you to participate in interactive features on our Site or any of our Services (when you choose to do so), to help improve the design, functionality, performance, and content of our Site and our Services and for the internal operational and administrative purposes of our Site and our Services. </p>
                    <p>We may use your Personal Data to contact you to send you information about our Services, and to notify you about changes or updates to our Site or Services.</p>
                    <p>We do not sell or rent your Personal Data, and will not disclose your Personal Data to any third party for advertising or marketing purposes, unless you have otherwise given us consent to do so. </p>
                    <p>If you interact with us through third-party social media sites and applications, we may have access to certain information from your social media account such as user name, profile picture, information about friends and followers, and content posted or viewed through the social media sites and applications. We may use this information to confirm identity, deliver personalised content or as part of the operation of our Site and our Services.</p>
                    <p><b>Web Tracking Data</b></p>
                    <p>We use Web Tracking Data to administer our Site and the Services, and for our internal operations, including to keep our Site safe and secure, to understand how well our Services are working as well as for troubleshooting, data analysis, testing, research, statistical and survey purposes. This allows us to help improve the design, functionality, performance, and content of our Site and our Services to you, personalise your user experience and measure overall effectiveness.</p>
                </li>
                <li>
                    <strong>THIRD PARTIES WE MAY WORK WITH</strong>
                    <p>We may share Personal Data and Web Tracking Data with selected third parties, such as our affiliates, business partners, suppliers and sub-contractors for the performance of any agreement we enter into with them, for the purposes of providing you with access and use of our Site and the Services. We may also make use of the Personal Data we have collected from you to enable us to comply with our advertisers’ wishes by displaying their advertisement to that target audience.</p>
                    <p>We may use your Personal Data and Web Tracking Data to create aggregated data for data analysis, testing, research, statistical and survey purposes. We may disclose such aggregated data, in an anonymous form, to: (a) analytics and search engine providers that assist us in the improvement and optimisation of our Site, and (b) advertisers and advertising networks that require the data to select and serve relevant advertisements to you and others through our Site. We do not disclose Personal Data about identifiable individuals to our advertisers, but we may provide them with aggregate information about our users. We may also use such aggregate information to help advertisers reach the kind of audience they want to target. </p>
                    <p>Notwithstanding anything to the contrary in this Privacy Policy, we reserve the right to use and disclose your Personal Data as well as any other information we may collect in connection with our Site and our Services: (a) to any prospective seller or buyer, or the seller or buyer of any of our businesses or assets, including as a result of any merger, acquisition, asset sale or similar transaction; (b) to any law enforcement agency, judicial authority, government authority or regulatory authority, to the extent required by law or legal process; and/or (c) if in our reasonable discretion, such use or disclosure is necessary for the purposes of protecting any of our legal rights, property or safety, or to protect third parties. </p>
                </li>
                <li>
                    <strong> CHILDREN'S PRIVACY</strong>
                    <p>We do not knowingly collect or retain Personal Data about persons under the age of 18 years. Any person who provides their Personal Data to us represents that they are 18 years of age and above. We encourage parents and legal guardians to monitor the activity of those under 18 years of age. </p>
                    <p>Parents or legal guardians of minors can contact us to review any Personal Data collected about their child or ward, have this information deleted, and/or request that there be no further collection or use of their child or ward’s Personal Data. We will take steps to verify the identity of anyone requesting Personal Data about a minor to ensure that the person is in fact the minor’s parent or legal guardian.</p>
                </li>
                <li>
                    <strong>SECURITY</strong>
                    <p>We have put in place procedures in an effort to safeguard and help prevent unauthorised access, maintain data security, and correctly use the information we collect. We also take reasonable steps to help make sure that third parties we work with protect the security of your Personal Data.</p>
                    <p>Where we have given you (or where you have chosen) a password which enables you to access certain parts of our Site, you are responsible for keeping this password confidential. We ask you not to share the password with anyone.</p>
                    <p>However, the transmission of information via the Internet is not completely secure. Although we will do our best to protect your Personal Data, we cannot guarantee the security of your data transmitted to our Site, and any transmission is at your own risk and it is possible that third parties may unlawfully access such personal information through a number of means despite our efforts.</p>
                </li>
                <li>
                    <strong>TRANSFER OF INFORMATION TO SINGAPORE OR ANY OTHER COUNTRIES</strong>
                    <p>Please be aware that by providing us with Personal Data, you understand and agree that: (a) your Personal Data may be transferred to and stored on servers located outside your resident jurisdiction; and (b) to the extent you are a resident of a country other than Singapore, you consent to the transfer of such data to Singapore or any countries for processing by us, our affiliates and/or any other organisation which we may choose, in accordance with this Privacy Policy. Wherever your personal information is transferred, stored or processed by us, we will take reasonable steps to safeguard the privacy of your personal information.</p>
                </li>
                <li>
                    <strong>LINKS TO THIRD PARTY SITES, CONTENT AND SERVICES</strong>
                    <p>Our Site may contain links to other websites, such as those of sponsors, advertisers, social networking platforms, and survey companies.</p>
                    <p>This Privacy Policy does not cover the privacy policies and information practices of any such third parties. These other websites are governed by their own privacy policies or information collection practices, which may be substantially different from ours. </p>
                    <p>For instance, these third party websites might offer content or games, or conduct contests or promotions that are marketed or advertised on our Sites. If you are interested in these third party offerings, you should consult those websites’ privacy notices. When you use any third party social media networking platforms and plug-ins, you may share your Personal Data with the third-party social media sites. You are encouraged to review the privacy policies and information collection practices of social media sites.</p>
                </li>
                <li>
                    <strong>YOUR RIGHTS</strong>
                    <p>You have the right to ask us not to process your Personal Data for marketing purposes. We will usually inform you before collecting your data if we intend to use your data for such purposes or if we intend to disclose your information to any third party for such purposes. You can exercise your right to prevent such processing and use by declining to check certain boxes on the forms we use to collect your Personal Data. You can also exercise the right at any time by contacting us.</p>
                    <p>The Personal Data Protection Act (No. 26 of 2012) (“Act”) gives you the right to access information which we hold about you. Your right of access can be exercised in accordance with the Act. Any access request may be subject to a fee to meet our costs in providing you with details of the information we hold about you, and we will notify you of what such fee will be after receiving your access request.</p>
                    <p>If you would like your Personal Data to be permanently removed from our servers or databases, please contact us with your request. We will promptly delete your account and you will no longer receive information or updates regarding our Services. The removal of your account and Personal Data from our servers and databases will not delete information stored in our data backups and archives, which we reserve the right to maintain for purposes of compliance with our legal obligations, but which we will delete in the normal course of our business.</p>
                </li>
                <li>
                    <strong>CHANGES TO THIS PRIVACY POLICY</strong>
                    <p>We may update this Privacy Policy from time to time. Any changes we may make to our Privacy Policy in the future will be posted on this page and, where appropriate, notified to you by e-mail. We encourage you to periodically check back to review this Privacy Policy to understand our current privacy practices.</p>
                </li>
                <li>
                    <strong>CONTACT</strong>
                    <p>If you have a comment, question or request regarding this Privacy Policy, please contact:</p>
                    <p><a href="mailto:bella.phua@bugisstreet.com.sg">bella.phua@bugisstreet.com.sg</a></p>
                    <p>
                        Effective Date: 23 Dec 2013
                        <br>
                        Date updated: 23 Dec 2013
                    </p>
                </li>
            </ol>
        </div>

    </div><!-- end of terms -->
</div>