<div style="text-align:center;"><img src="<?php echo $this->getSkinUrl('images/seller_banner.jpg') ?>" style="width:100%; max-width:500px;" alt="top"></div>
<div id="faq" class="content">
    <div id="steps" style="margin:0 auto;max-width:700px;">
        <div id="step1" style="float:left;padding-top:15px;width:33%;">
            <a href="<?php echo $this->getUrl('customer/account/create') ?>"><img src="<?php echo $this->getSkinUrl('images/seller_open.jpg') ?>" alt="top" width="100%"></a>
        </div>
        <div id="step2" style="float:left;padding-top:15px;width:33%;">
            <img src="<?php echo $this->getSkinUrl('images/seller_list.jpg') ?>" alt="top" width="100%">
        </div>
        <div id="step3" style="float:left;padding-top:15px;width:33%;">
            <img src="<?php echo $this->getSkinUrl('images/seller_manage.jpg') ?>" alt="top" width="100%">
        </div>
    </div>
    <div style="text-align:center;"><img src="<?php echo $this->getSkinUrl('images/seller_banner2.jpg') ?>" style="width:100%; max-width:500px;margin-top:30px;" alt="top"></div>
    <div id="whysell" style="margin:0 auto;max-width:650px;padding-left:10px;padding-right:10px;">
        <ol>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;">NO subscription fees, NO registration fee, NO listing fees, NO risk.</span></li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;">Reach out to a bigger audience with us</span>Bugis Street is famous locally and internationally for providing the most unique shopping experience both offline and online. Doesn't hurt that we rank really high on Google too. It's all about the numbers!</li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;">Super fast and easy registration</span>Set up your online business in minutes!</li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;">Sell anytime and anywhere</span>Our website is fully optimized for mobile, so shoppers can buy your stuff in front of a computer, or on the go with their smart devices.</li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;">Flexibility</span> Manage your online business at your own pace with the simple and powerful seller dashboard that we developed just for you.</li>
        </ol>
    </div>

    <div style="text-align:center;"><img src="<?php echo $this->getSkinUrl('images/seller_banner3.jpg') ?>" style="width:100%; max-width:500px;margin-top:30px;" alt="top"></div>
    <div id="whysell1" style="margin:0 auto;max-width:650px;padding-left:10px;padding-right:10px;">
        <ol>

            <li style="padding-bottom:20px;">
                <span style="font-size:1.3em;clear:both;display:block;font-weight:bold;padding-left:30px;">
                    What can I sell?</span>
                <span style="display:block;padding-left:30px;">The Bugis Street Online Store is a marketplace for anybody looking to start or grow an online business. We currently have 5 main categories, comprising: Women, Men, Kids &amp; Baby, Electronics, and Gifts. If the item that you want to sell does not belong to any of the available categories, please <a href="<?php echo $this->getUrl('contacts/') ?>">Contact Us</a> and hang in there. We can always add new categories to make the store even more exciting. If you wish to learn more about what can't be sold on the Bugis Street Online Store, <a href="javascript:ReverseDisplay('uniquename')">click here</a> to read more.</span></li>

            <div id="uniquename" style="display:none;">

                <p></p><ol style="padding-left:5%;">
                    <span style="font-size:1em;clear:both;display:block;font-weight:bold;padding-top:0px;padding-bottom:20px;">The Retailer shall ensure that the following Products will not be sold and/or listed on the Electronic Marketplace Platform:</span>
                    <li style="padding-bottom:20px;">a) Products that contain misleading advertising or false claims, whether on the Product label itself, in the Product description page on the Electronic Marketplace Platform or otherwise;</li>
                    <li style="padding-bottom:20px;">b) Products that infringe third-party rights, including property rights and intellectual property rights;</li>
                    <li style="padding-bottom:20px;">c) Products that are obscene or vulgar;</li>
                    <li style="padding-bottom:20px;">d) Industrial Products which have failed to pass inspection/examination; </li>
                    <li style="padding-bottom:20px;">e) Illegal copies of videos, music or games;</li>
                    <li style="padding-bottom:20px;">f) Stolen or lost Products;</li>
                    <li style="padding-bottom:20px;">g) Products which Singapore Customs classifies as "prohibited goods" or "controlled goods"; or</li>
                    <li style="padding-bottom:20px;">h) Any goods for which an on-line transaction to offer to sell, sell and/or purchase such goods is prohibited under applicable laws and regulations</li>
                </ol>
                <p></p>
            </div>


            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;padding-left:30px;">What are the sign up, subscription and listing fees?</span>
                <span style="display:block;padding-left:30px;">The Bugis Street Online Store does not charge any sign up, subscription, nor listing fees.</span></li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;font-weight:bold;padding-left:30px;">Do you take a percentage of each sale?</span><span style="display:block;padding-left:30px;">Since it is free to list your item, you only pay when you sell! Whenever you make a sale on the Bugis Street Online Store, we take a 13% commission on your sales. Payment gateway charges are applicable as well. <a href="javascript:ReverseDisplay('uniquename2')">Click here</a> for a more comprehensive explanation of the percentages.</span></li>
            
                        <div id="uniquename2" style="display:none;">

                <p></p><ol style="padding-left:5%;">
                    <span style="font-size:1em;clear:both;display:block;font-weight:bold;padding-top:0px;padding-bottom:20px;">Percentages:</span>
                    <li style="padding-bottom:20px;">Seller gives Bugis Street Online Store = 13% commission of transacted amount + 7% GST on that Commission  + Payment gateway charges</li>
                </ol>
                <p></p>
            </div>
            
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;padding-left:30px;font-weight: bold;">How would I know if someone confirms a purchase online?</span><span style="display:block;padding-left:30px;">Whenever somebody buys something from your online store, you will receive a notification via email immediately. Don't forget to check that our emails don't end up in your junk folder!</span></li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;background-size:24px;padding-left:30px;font-weight: bold;">How do I get paid?</span><span style="display:block;padding-left:30px;">Buyers pay for purchases with their credit/debit card, or eNETS direct debit in Singapore dollars, and you will receive your earnings to your bank account within 30 days of the transaction in Singapore dollars as well.</span></li>
            <li style="padding-bottom:20px;"><span style="font-size:1.3em;clear:both;display:block;background-size:24px;padding-left:30px;font-weight: bold;">Still have more questions?</span><span style="height:24px;display:block;padding-left:30px;">Do not hesitate to <a href="/contacts/" target="_blank">contact us</a>. We are here to help.</span></li>
        </ol>
    </div>

</div>
<script>
    var header_h = jQuery(".topnav-wrapper").height() + 0;
    var changepoint = parseInt(header_h  * 2);
    function header_transform() {
        window_y = jQuery(window).scrollTop();
        if(window_y > changepoint) {
            jQuery('.backtotop').show();
        } else {
            jQuery('.backtotop').hide();
        }
    }

    jQuery(function() {
        jQuery( ".accordion" ).accordion({heightStyle: "content",collapsible: true, active: false,header: "h3"});
        jQuery('.anchor').click(function(){
            var sto = jQuery(this).attr("href");
            jQuery('html, body').animate({scrollTop:jQuery(sto).position().top}, 'slow');
            return false;
        });

        jQuery('.backtotop').click(function(){
            jQuery('html, body').animate({scrollTop:0}, 'slow');
            return false;
        });

        jQuery(window).scroll(function() {
            header_transform();
        });
    });
</script>

<script type="text/javascript" language="JavaScript"><!--
    function HideContent(d) {
        document.getElementById(d).style.display = "none";
    }
    function ShowContent(d) {
        document.getElementById(d).style.display = "block";
    }
    function ReverseDisplay(d) {
        if(document.getElementById(d).style.display == "none") { document.getElementById(d).style.display = "block"; }
        else { document.getElementById(d).style.display = "none"; }
    }
    //--></script>