<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/style-m.css') ?>">
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ui.js') ?>"></script>
<div id="terms" class="content">
    <div class="page-title">
        <h1>TERMS OF USE</h1>
        <div class="clear"></div>
    </div>

    <div class="accordion ui-accordion ui-widget ui-helper-reset" role="tablist">

        <div class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-accordion-1-header-0" aria-controls="ui-accordion-1-panel-0" aria-selected="false" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>
            <ol>
                <li>
                    <strong>Introduction</strong>
                    <ol>
                        <li>www.bugisstreet.com.sg is a site operated by Bugis Street Online Pte. Ltd. ("we", “us” or “our”). We are registered in Singapore under company number 201218923H and have our registered office at 3 New Bugis Street, #03-01, Singapore 188867.</li>
                        <li>These Terms of Use sets out the terms on which you may make use of our website www.bugisstreet.com.sg (“our Site”), whether as a guest or a registered user. Use of our Site includes accessing, browsing, or registering to use our Site.</li>
                        <li>Please read these Terms of Use carefully before you start to use our Site, as these will apply to your use of our Site. We recommend that you print a copy of this for future reference. </li>
                        <li>By using our Site, you confirm that you agree to comply with and will be bound by these Terms of Use and our Privacy Policy.</li>
                        <li>If you do not agree to these Terms of Use or our Privacy Policy, you must not use our Site.</li>
                    </ol>
                </li>
                <li>
                    <strong>Changes to terms and site</strong>
                    <ol>
                        <li>We may revise these Terms of Use at any time by amending this page. Please check this page from time to time to take notice of any changes we made, as they are binding on you. </li>
                        <li>We may update our Site from time to time, and may change the content at any time. However, please note that any of the content on our Site may be out of date at any given time, and we are under no obligation to update it. </li>
                    </ol>
                </li>
                <li>
                    <strong>Accessing our Site</strong>
                    <ol>
                        <li>Access to our Site is made available free of charge. </li>
                        <li>We do not guarantee that our Site, or any content on it, will always be available or be uninterrupted. We may, for any reason, suspend, withdraw, discontinue or change all or any part of our Site without notice. </li>
                        <li>We will not be liable to you for any loss or damage suffered by reason of your inability to access our Site at any time or for any period.</li>
                    </ol>
                </li>
                <li>
                    <strong>Your account and password</strong>
                    <ol>
                        <li>You may choose to register yourself as a member by creating a user account or by logging into our Site using your Facebook account. You must treat your user account, password and Facebook login details (collectively, “account information”) as confidential and must not disclose them to any third party. </li>
                        <li>If you know or suspect that anyone other than you knows about the details of your account information, or may otherwise have unauthorised access to your user account or Facebook account, you must promptly notify us at online@bugisstreet.com.sg.</li>
                        <li>You agree to accept responsibility for all activities on our Site that occur under your user account or Facebook account. You agree to bear all liability and fully indemnify us against all actions, claims, proceedings, costs and damages and all legal costs or other expenses arising out of any activity that occurs under your user account or Facebook account. </li>
                        <li>We have the right to suspend, disable or terminate your user account or to prevent you from using our Site via your Facebook account at any time, if in our reasonable opinion, you have failed to comply with any of the provisions of these Terms of Use. We reserve the right to terminate your user account if it has been inactive for more than one year. </li>
                    </ol>
                </li>
                <li>
                    <strong>Intellectual property rights</strong>
                    <ol>
                        <li>We are the owner of all intellectual property rights in our Site and in the material published on it.  Those works are protected by copyright laws and treaties around the world.  All such rights are reserved. </li>
                        <li>You agree not to copy, reproduce, modify, create derivative works from, distribute, or publicly display any content from our Site without our expressed written permission. In the event that such permission is given, our status as the author of the content on our Site must always be acknowledged. </li>
                        <li>Notwithstanding clause 5(b), you are permitted to share information about the products sold on our Site on social media and other platforms. </li>
                    </ol>
                </li>
                <li>
                    <strong>Prohibited uses</strong>
                    <ol>
                        <li>
                            You may use our Site only for lawful purposes.  In using our Site, you will not:
                            <ol>
                                <li>breach any applicable local, national or international law or regulation;</li>
                                <li>engage in activity that is unlawful or fraudulent, or has any unlawful or fraudulent purpose or effect;</li>
                                <li>use it for the purpose of harming or attempting to harm minors in any way;</li>
                                <li>send, knowingly receive, upload, download, use or re-use any material which does not comply with our content standards as set out in clause 9;</li>
                                <li>fail to make payment for products purchased by you, unless you are entitled to reject the products in accordance with our Terms and Conditions of Sale;</li>
                                <li>manipulate the price of any item or interfere with any seller’s product listings;</li>
                                <li>take any action that may undermine our Site’s feedback or ratings systems;</li>
                                <li>harvest or otherwise collect information about users, including email addresses, without their consent; </li>
                                <li>use it to transmit, or procure the sending of, any unsolicited or unauthorised advertising or promotional material or any other form of similar solicitation; or</li>
                                <li>knowingly transmit any data, send or upload any material that contains viruses, Trojan horses, worms, keystroke loggers, spyware, adware or any other harmful programmes designed to adversely affect the operation of any computer software or hardware.</li>
                            </ol>
                        </li>
                        <li>
                            You agree not to access without authority, interfere with, damage or disrupt:
                            <ol>
                                <li>any part of our Site;</li>
                                <li>any equipment or network on which our Site is stored; </li>
                                <li>any software used in the provision of our Site; or </li>
                                <li>any equipment or network or software owned or used by any third party.</li>
                            </ol>
                        </li>
                    </ol>
                </li>
                <li>
                    <strong>Uploading content to our Site</strong>
                    <ol>
                        <li>You warrant that any content you upload to our Site (including reviews, comments and photos) complies with our content standards as set out in clause 9. You will be liable to us and indemnify us against all actions, claims, proceedings, costs and damages and all legal costs or other expenses arising out of your breach of this warranty. </li>
                        <li>If you do upload content, you are deemed to have granted us a non-exclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. </li>
                        <li>We have the right to disclose your identity to any third party who is claiming that any content posted or uploaded by you to our Site constitutes a violation of their intellectual property rights, or any other legal rights. </li>
                        <li>You represent and warrant that you own or otherwise control all of the rights to the content that you post, that the content is accurate, that use of the content you supply does not violate this Terms of Use and will not cause injury to any person or entity. We will not be responsible or liable for the content or accuracy of any content posted by you on our Site and you agree bear all liability and indemnify us against all actions, claims, proceedings, costs and damages and all legal costs or other expenses arising out of your breach of this warranty.</li>
                        <li>We have the right to remove any content that you upload to our Site if, in our opinion, the content does not comply with our content standards as set out in clause 9.</li>
                    </ol>
                </li>
                <li>
                    <strong>Linking to our Site</strong>
                    <ol>
                        <li>You may link to our Site, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it. When linking to our Site, our Site must not be framed on any other site. </li>
                        <li>You must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists. </li>
                    </ol>
                </li>
                <li>
                    <strong>Content standards</strong>
                    <ol>
                        <li>
                            All content that you upload on our Site must:
                            <ol>
                                <li>be accurate (where they state facts);</li>
                                <li>be genuinely held (where they state opinions); and</li>
                                <li>comply with applicable law in Singapore and in any country from which they are posted.</li>
                            </ol>
                        </li>
                        <li>
                            All content that you upload on our Site must not:
                            <ol>
                                <li>contain any material which is defamatory of any person;</li>
                                <li>contain any material which is obscene, offensive, hateful or inflammatory;</li>
                                <li>promote sexually explicit material;</li>
                                <li>promote violence;</li>
                                <li>promote discrimination based on race, sex, religion, nationality, disability, sexual orientation or age;</li>
                                <li>infringe any copyright, database right or trade mark of any other person;</li>
                                <li>be likely to deceive any person;</li>
                                <li>be made in breach of any legal duty owed to a third party, such as a contractual duty or a duty of confidence;</li>
                                <li>promote any illegal activity;</li>
                                <li>be threatening, abuse or invade another’s privacy, or cause annoyance, inconvenience or needless anxiety;</li>
                                <li>be likely to harass, upset, embarrass, alarm or annoy any other person;</li>
                                <li>be used to impersonate any person, or to misrepresent your identity or affiliation with any person;</li>
                                <li>give the impression that they emanate from us, if this is not the case; or</li>
                                <li>advocate, promote or assist any unlawful act such as copyright infringement or computer misuse.</li>
                            </ol>
                        </li>
                    </ol>
                </li>
                <li>
                    <strong>Suspension and termination</strong>
                    <ol>
                        <li>We will determine, in our discretion, whether there has been a breach of these Terms of Use through your use of our Site.</li>
                        <li>
                            When a breach of these Terms of Use has occurred, we may take such action as we deem appropriate, including:
                            <ol>
                                <li>the immediate, temporary or permanent withdrawal of your right to use our Site;</li>
                                <li>the immediate, temporary or permanent removal of any posting or material uploaded by you to our Site;</li>
                                <li>the issue of a warning to you;</li>
                                <li>legal action against you; and</li>
                                <li>the disclosure of such information to law enforcement authorities as we reasonably feel is necessary.</li>
                            </ol>
                        </li>
                    </ol>
                </li>
                <li>
                    <strong>Limitation of our liability</strong>
                    <ol>
                        <li>
                            To the fullest extent permitted by law, we will not be liable for:
                            <ol>
                                <li>any loss or damage arising from any material or data sent or received or not sent or received or any transactions entered into through our Site; </li>
                                <li>any threatening, defamatory, obscene, offensive or illegal content or conduct of any other party or any infringement of another party’s rights, including intellectual property rights; </li>
                                <li>any special, incidental, indirect, punitive or consequential damages of any kind, or any damages whatsoever, whether in contract, tort, strict liability or otherwise arising out of or in connection with the use of, or inability to use our Site; </li>
                                <li>any loss or damage caused by a virus, distributed denial-of-service attack, or other technologically harmful material that may infect your computer equipment, computer programmes, data or other proprietary material due to your use of our Site or to your downloading of any content on it, or on any website linked to it; or</li>
                                <li>any loss or damage arising from the content of websites linked on our Site. </li>
                            </ol>
                        </li>
                    </ol>
                </li>
                <li>
                    <strong>No Warranties</strong>
                    <ol>
                        <li>In all transactions made on our Site, we do not warrant or represent the quality, safety, usability, functionality or legality of products advertised, the truth or accuracy of the content on the product description page, the ability of the seller to deliver the products.</li>
                    </ol>
                </li>
                <li>
                    <strong>Indemnity</strong>
                    <ol>
                        <li>You will indemnify and hold us (and our officers, directors, agents, subsidiaries, joint ventures and employees), harmless from any claim or demand, including legal fees, made by any third party due to or arising out of your breach of these Terms of Use, or your violation of any law or the rights of any third party. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with us in asserting any available defenses.</li>
                        <li>We will not interfere and indemnify you for any losses arising from disputes between you and the seller over any transaction entered into or over any information on products listed on our Site. However, we may at our discretion intervene in such dispute through our own dispute mediation center (or customer service center) for the purpose of reasonable and smooth settlement, in which case you shall in good faith respect the center’s decision to the fullest extent practicable. </li>
                        <li>You undertake and warrant that you will not bring or allow to be brought any legal claim whether directly or indirectly arising in connection with your use of this Site or a breach of these Terms of Use, against Bugis Street Development Pte Ltd.</li>
                    </ol>
                </li>
                <li>
                    <strong>Viruses</strong>
                    <ol>
                        <li>We do not guarantee that our Site will be secure or free from bugs or viruses. We will not be liable to you and any other party for any loss or damage arising out of any bugs or viruses originating from our Site. </li>
                        <li>You are responsible for configuring your information technology, computer programmes and platform in order to access our Site. You should use your own virus protection software.</li>
                        <li>
                            You must not carry out the following activities against our Site:
                            <ol>
                                <li>misuse our Site by knowingly introducing viruses, trojans, worms or other material which is malicious or technologically harmful;</li>
                                <li>gain, or attempt to gain unauthorised access to our Site, the server on which our Site is stored or any server, computer or database connected to our Site; or</li>
                                <li>attack our Site via a denial-of-service attack or a distributed denial-of service attack. </li>
                            </ol>
                        </li>
                    </ol>
                </li>
                <li>
                    <strong>Third party links and resources on our Site</strong>
                    <ol>
                        <li>Where our Site contains links to other sites and resources provided by third parties, these links are provided for your information only. We have no control over the contents of those sites or resources and we make no representations, warranties or guarantees that the content contained therein is accurate, complete or up-to-date. We will not be liable for any loss or damage caused by your reliance on such third party content. </li>
                    </ol>
                </li>
                <li>
                    <strong>Data Protection</strong>
                    <ol>
                        <li>We are committed to protecting and respecting your privacy. Our Privacy Policy sets out in full how your personal data will be handled. </li>
                        <li>We will not be liable for any loss or damage arising out of the collection, use, disclosure or any other kind of processing in relation to your personal data, if we have complied with our data protection obligations under applicable laws and regulations, including the provisions of the Personal Data Protection Act 2012 (Act 26 of 2012).</li>
                    </ol>
                </li>
                <li>
                    <strong>No Warranties</strong>
                    <ol>
                        <li>Although we make reasonable efforts to update the content on our Site, we make no representations, warranties or guarantees, whether express or implied, that the content on our Site is accurate, complete or up-to-date. We will not be liable for any loss or damage caused by your reliance on information obtained through our Site. It is your responsibility to evaluate the accuracy, completeness and usefulness of any content provided before taking, or refraining from, any action on the basis of any content on our Site. </li>
                    </ol>
                </li>
                <li>
                    <strong>No Agency</strong>
                    <ol>
                        <li>No agency, partnership, joint venture, employer-employee or franchisor-franchisee relationship is intended, exists or is created between us and you or any other party using our Site. </li>
                    </ol>
                </li>
                <li>
                    <strong>Severance</strong>
                    <ol>
                        <li>If any part of these Terms of Use is determined to be invalid or unenforceable pursuant to applicable law, the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms of Use will continue in effect.</li>
                    </ol>
                </li>
                <li>
                    <strong>Waivers/Rights and Remedies</strong>
                    <ol>
                        <li>No failure or delay by us in exercising any right or remedy provided by law under or pursuant to these Terms of Use will impair such right or remedy or operate or be construed as a waiver or variation of it or preclude its exercise at any subsequent time and no single or partial exercise of any such right or remedy will preclude any other or further exercise of it or the exercise of any other right or remedy.</li>
                        <li>Our rights and remedies under these Terms of Use will not be affected, and your liabilities under these Terms of Use will not be released, discharged or impaired by any event or matter whatsoever, other than a specific and duly authorised written waiver or release given by us.</li>
                    </ol>
                </li>
                <li>
                    <strong>No Third Party Rights</strong>
                    <ol>
                        <li>A person who is not a party to this Terms of Use has no right under the Contracts (Rights of Third Parties) Act (Cap. 53B) to enforce any term provided in these Terms of Use. </li>
                    </ol>
                </li>
                <li>
                    <strong>Jurisdiction</strong>
                    <ol>
                        <li>These Terms of Use will be governed by and interpreted in accordance with the laws of Singapore.</li>
                        <li>The courts of Singapore will have exclusive jurisdiction over any legal action or proceedings arising out of, with respect to, or in connection with any disputes over these Terms of Use. </li>
                    </ol>
                </li>
                <li>
                    <strong>Contact us</strong>
                    <ol>
                        <li>To contact us, please email <a href="mailto:online@bugisstreet.com.sg" target="_blank">online@bugisstreet.com.sg</a>.</li>
                    </ol>
                </li>

            </ol></div>
    </div><!-- end of terms -->
</div>
<script>
    jQuery(function() {
        jQuery( ".accordion" ).accordion({heightStyle: "content",collapsible: true, active: false});
    });
</script>
