<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ias.js') ?>"></script>
<script type="text/javascript">
   jQuery(document).ready(function(){
       var flag = false;
       var c_flag = false;
       jQuery(".filter-filters").click(function(){
           //console.log(c_flag)
           if (c_flag == false){
               c_flag = true;
               flag = true;
           }else{
               c_flag = false;
               flag = false;

           }
       });
       jQuery(".leftnav-menutrigger").click(function(){
           jQuery(".mb-mana-catalogsearch-leftnav").removeClass("test-search-mana");
           jQuery(".filter-over").removeClass("toggled");
       });
       jQuery(".filter-sort").click(function(){
            flag = false;
           c_flag = true;
       });
//       jQuery(window).scroll(function(){
//           //console.log(flag)
//           if (flag){
//
//               jQuery(".mb-mana-catalogsearch-leftnav").addClass("test-search-mana");
//               jQuery(".filter-over").addClass("toggled");
//
//           }else{
//               jQuery(".mb-mana-catalogsearch-leftnav").removeClass("test-search-mana");
//               jQuery(".filter-over").removeClass("toggled");
//
//           }
//       });

       var ias= jQuery.ias({
           container: '.category-products',
           item: 'ul.products-grid',
           pagination: '.pages',
           next: 'a.next',
           loader: '<img src="<?php echo $this->getSkinUrl('images/preloader.gif'); ?>" height="80" width="80" class="preloader"/>',
       });
       ias.extension(new IASSpinnerExtension());            // shows a spinner (a.k.a. loader)
       ias.extension(new IASTriggerExtension()); // shows a trigger after page 3
       ias.extension(new IASNoneLeftExtension({
              // override text when no pages left
       }));


   });


</script>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
$_SESSION['max_product_price'] = $_productCollection->getMaxPrice();
?>






<?php $cate_id =  Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
$products_count = Mage::getModel('catalog/category')->load($cate_id)->getProductCount();
?>
<?php if(!$_productCollection->count()):?>
    <div class="block_filter">
        <ul class="productlisting-filters">
            <li class="filter-filters">
                <a id="filter-trig"><span class="label">Filter</span></a>
            </li>
            <li class="filter-sort">
                <a><span class="label">Sort</span></a>
            </li>
        </ul>

        <div class="border-bottom"></div>
        <div class="filter-over clearfix" style="display: none;" id="filters">
            <div class="filter-mobile-heading">
                <h3>Filter By</h3>

                <div class="mobilefilter-close"></div>
            </div>
            <?php  //echo $this->getLayout()->createBlock('mana_filters/view')->setTemplate('manapro/filteradvanced/view.phtml')->toHtml(); ?>
        </div>
        <div class="sort-over">
            <ul>
                <li onclick="dosort('created_at', 'desc');">New Arrivals</li>
                <li onclick="dosort('price', 'desc');">Price (High to Low)</li>
                <li onclick="dosort('price', 'asc');">Price (Low to High)</li>
                <li onclick="dosort('name', 'asc');">Name (A-Z)</li>
                <li onclick="dosort('most_viewed', 'desc');">Most Viewed</li>
                <li onclick="dosort('bestsellers', 'desc');">Popular</li>
            </ul>
        </div>
    </div>

    <div class="category-products">
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col content clearfix bso-product-listing product-columns" style="background-color: white; min-height: 360px">
                <p class="note-msg" style="color:#000; padding-left: 30px; margin-top: 50px;">

                    We could not find any matches for your search ''.

                    <br>
                    <br>

                    Search Tips

                    <br>

                    1. Make sure all words are spelt correctly

                    <br>

                    2. Try using fewer words

                    <br>

                    3. Try using more general keywords

                    <br>

                    4. Try different keywords

                </p>
            </ul>

    </div>

<?php else: ?>
<div class="block_filter">
        <ul class="productlisting-filters">
        <?php if($products_count!=1):?>
            <li class="filter-filters">
                <a id="filter-trig"><span class="label">Filter</span></a>
            </li>
        <?php endif; ?>
                <li class="filter-sort">
                    <a><span class="label">Sort</span></a>
                </li>
            </ul>


            <div class="border-bottom"></div>
            <div class="filter-over clearfix" style="display: none;" id="filters">
                <div class="filter-mobile-heading">
                    <h3>Filter By</h3>

                    <div class="mobilefilter-close"></div>
                </div>
                        <?php  //echo $this->getLayout()->createBlock('mana_filters/view')->setTemplate('manapro/filteradvanced/view.phtml')->toHtml(); ?>


            </div>
            <div class="sort-over">
                <ul>
                    <li onclick="dosort('created_at', 'desc');">New Arrivals</li>
                    <li onclick="dosort('price', 'desc');">Price (High to Low)</li>
                    <li onclick="dosort('price', 'asc');">Price (Low to High)</li>
                    <li onclick="dosort('name', 'asc');">Name (A-Z)</li>
                    <li onclick="dosort('most_viewed', 'desc');">Most Viewed</li>
                    <li onclick="dosort('bestsellers', 'desc');">Popular</li>
                </ul>
            </div>
            <!--filter-->
    </div>





    <div class="category-products">
    <div class="catagory_name">
    <?php //echo Mage::getModel('catalog/category')->load($this->getCategoryId())->getName(); ?>
        </div>
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list" style="background-color: white">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image">
                            <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                            <?php $_imgSize = 480; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        </a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <div class="product-primary">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                                title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                    </h2>
                                    <?php if ($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                    <?php endif; ?>
                                    <?php
                                    // Provides extra blocks on which to hang some features for products in the list
                                    // Features providing UI elements targeting this block will display directly below the product name
                                    if ($this->getChild('name.after')) {
                                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                            $_nameAfterChild->setProduct($_product);
                                            echo $_nameAfterChild->toHtml();
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="product-secondary">
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                </div>
                                <div class="product-secondary">
                                    <?php if (!$_product->canConfigure() && $_product->isSaleable()): ?>
                                        <p class="action">
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                    class="button btn-cart"
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                            </button>
                                        </p>
                                    <?php elseif ($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                        <p class="action"><a title="<?php echo $this->__('View Details') ?>"
                                                             class="button"
                                                             href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                                        </p>
                                    <?php else: ?>
                                        <p class="action availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                                   class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                            </li>
                                        <?php endif; ?>
                                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"
                                                                                    class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                                            </li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped ?>"
                                       class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col content clearfix bso-product-listing product-columns"
                id="productlist_content" style="background-color: white; min-height: 360px">
                <?php $i = 0;
                foreach ($_productCollection as $_product): ?>
                    <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?> box individual-item productitems">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image">
                            <?php $_imgSize = 480; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        </a>

                        <div class="desc">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"
                               class="product-description clearfix">
                                <div class="desc-left">
                        <span class="item-name">
                        <?php
                            $product_name = $_helper->productAttribute($_product, $_product->getName(), 'name');
                            echo Mage::helper('core/string')->truncate($product_name, '50');
                        ?>
                            </span>
                                </div>
                                <div class="desc-right">
                                <span class="item-price">
                                  <?php echo $this->getPriceHtml($_product, true) ?>                           </span>
                                </div>


                            </a>
                        </div>
                    </li>
                    <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
                <?php endforeach ?>

            </ul>
            <script
                type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
    function updateQueryStringParameter(uri, key, value) {
        var re = new RegExp("([?|&])" + key + "=.*?(&|#|$)", "i");
        if (uri.match(re)) {
            return uri.replace(re, '$1' + key + "=" + value + '$2');
        } else {
            var hash = '';
            var separator = uri.indexOf('?') !== -1 ? "&" : "?";
            if (uri.indexOf('#') !== -1) {
                hash = uri.replace(/.*#/, '#');
                uri = uri.replace(/#.*/, '');
            }
            return uri + separator + key + "=" + value + hash;
        }
    }
    function removeQueryStringParameter(url, parameter) {
        var urlparts = url.split('?');
        if (urlparts.length >= 2) {
            var prefix = encodeURIComponent(parameter) + '=';
            var pars = urlparts[1].split(/[&;]/g);
            for (var i = pars.length; i-- > 0;) {
                if (pars[i].lastIndexOf(prefix, 0) !== -1) {
                    pars.splice(i, 1);
                }
            }
            url = urlparts[0] + '?' + pars.join('&');
            return url;
        } else {
            return url;
        }
    }
    function dosort(order, dir) {
        document.location = updateQueryStringParameter(updateQueryStringParameter(document.URL, 'order', order), 'dir', dir);
    }
    function load_filters() {
        var url = document.URL;
        var colorfilters = jQuery('.swatch-color.active').map(function () {
            return jQuery(this).data('value');
        }).get();
        if (colorfilters.length > 0) {
            url = updateQueryStringParameter(url, 'color', colorfilters.join(","));
        } else {
            url = removeQueryStringParameter(url, 'color');
        }
        var sizefilters = jQuery('.size-box.active').map(function () {
            return jQuery(this).data('value');
        }).get();
        if (sizefilters.length > 0) {
            url = updateQueryStringParameter(url, 'clothes_size', sizefilters.join(","));
        } else {
            url = removeQueryStringParameter(url, 'clothes_size');
        }
        var vendorfilters = jQuery('input[name=a-d]:checked').map(function () {
            return jQuery(this).val();
        }).get();
        if (vendorfilters.length > 0) {
            url = updateQueryStringParameter(url, 'vendorname', vendorfilters.join(","));
        } else {
            url = removeQueryStringParameter(url, 'vendorname');
        }
        url = updateQueryStringParameter(url, 'price', jQuery('.price-slider').slider('values').join(","));
        document.location = url;
    }</script>
