<script type="text/javascript">
    /*jQuery(document).ready(function () {
        slider = jQuery('.bxslider').bxSlider();

        jQuery('.bxslider').swipe({swipeLeft: swipeLeft, swipeRight: swipeRight, threshold: 0});
    });*/
    function swipeLeft(event) {
        slider.goToNextSlide();
    }
    function swipeRight(event) {
        slider.goToPrevSlide();
    }


</script>

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
$helper = Mage::helper('marketplace');
$productowner = Mage::getModel('marketplace/product')->isCustomerProduct($_product['entity_id']);
$html_shipping = '<ul class="custom_ship">';
if ($productowner['userid'] != "") {
    $rowsocial = Mage::getModel('marketplace/userprofile')->getPartnerProfileById($productowner['userid']);
    $_seller = Mage::getModel('customer/customer')->load($productowner['userid']);
    $_cursym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
    $method1 = $_seller->getData('mp_shipping_charge_title');
    $method2 = $_seller->getData('mp_shipping_charge_title2');
    $method3 = $_seller->getData('mp_shipping_charge_title3');

    $cost1 = $_product->getData('mp_shipping_charge');
    $cost2 = $_product->getData('mp_shipping_charge2');
    $cost3 = $_product->getData('mp_shipping_charge3');
    $html_shipping .= '<li>' . $method1 . ' - <strong>' . $_cursym . $cost1 . '</strong></li>';
    $html_shipping .= '<li>' . $method2 . ' - <strong>' . $_cursym . $cost2 . '</strong></li>';
    $html_shipping .= '<li>' . $method3 . ' - <strong>' . $_cursym . $cost3 . '</strong></li>';
}
$html_shipping .= '</ul>';

?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="content">


    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
    <div class="product-view">
        <div class="product-essential">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post"
                  id="product_addtocart_form" <?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <?php echo $this->getBlockHtml('formkey') ?>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
                    <input type="hidden" name="related_product" id="related-products-field" value=""/>
                </div>
                <div class="col2">
                    <!--<label>
                        About This Retailer
                    </label>-->
                    <?php if ($productowner['userid'] != ""): ?>
                        <div style="height: 90px" id="demoretailer243" class="retailer premium vendordiv">
                            <?php
                            $logo = $rowsocial['logopic'] == '' ? "noimage.png" : $rowsocial['logopic'];
                            $logo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'avatar/' . $logo;
                            ?>

                            <div class="r-name">
                                <!--<div style="float:left;border:1px solid #CCC;-webkit-box-shadow: 0 5px 3px -3px black;-moz-box-shadow: 0 5px 3px -3px black;box-shadow: 0 5px 3px -3px black;">
                                <a href="<?php /*echo $this->getUrl('marketplace/seller/profile'). $rowsocial['profileurl'] */ ?>" >
                                    <img width="60" class="bannerpicrs-remove" src="<?php /*echo $logo;*/ ?>" />
                                </a>
                            </div>-->
                                <div style="float:left;padding-left:5px;">
                                    <a class="shop-title" target="_blank"
                                       style="color:#333; font-weight: bold; font-size: 1.3em;"
                                       href="<?php echo $this->getUrl('marketplace/seller/profile') . $rowsocial['profileurl'] ?>">
                                        <?php //echo $rowsocial['firstname']." ".$rowsocial['lastname'] ?>
                                        <?php echo $rowsocial['shoptitle'] ?>
                                    </a>
                                    <br>
                                    <a target="_blank"
                                       style="font-size:0.8em;padding:3px;border:1px solid;font-weight:normal; color: #333;margin-right: 5px"
                                       href="<?php echo rtrim($this->getUrl('seller_detail?seller=' . $rowsocial['profileurl']), '/'); ?>">
                                        See All Products
                                    </a>
                                    <a target="_blank"
                                       style="font-size:0.8em;padding:3px;border:1px solid;font-weight:normal; color: #333"
                                       href="<?php echo $this->getUrl('marketplace/seller/profile') . $rowsocial['profileurl'] ?>">
                                        Shop Info
                                    </a>
                                </div>
                            </div>
                        </div>

                    <?php endif; ?>
                    <div>
                        <?php
                        if ($productowner['userid'] != "") {
                            if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                                $customerData = Mage::getSingleton('customer/session')->getCustomer();
                                $customerid = $customerData->getId();
                                $collection = Mage::getModel('log/visitor_online')->prepare()->getCollection()
                                    ->addFieldToFilter('customer_id', array('eq' => $productowner['userid']));
                                if ($customerid == $productowner['userid']) {
                                    $collection->addFieldToFilter('customer_id', array('neq' => $customerid));
                                }
                                $collection->addFieldToSelect('customer_id');
                                $collection->distinct(true);
                                $collection->addCustomerData();
                                $buyerids = array();
                                foreach ($collection as $buyer) {
                                    $buyer = Mage::getModel('customer/customer')->load($buyer->getCustomerId()); ?>
                                    <div class="wk_cs_chat_buddies c_buddies" id="list-<?php echo $buyer->getId() ?>">
                                        <span>Chat Online</span>
                                        <span id="wk_cs_admin_signal" class="wk_cs_signal_on c_l"></span>
                                        <span class="wk_cs_buddy_name cs_name"><?php echo $buyer->getName(); ?></span>
                                    </div>
                                    <?php
                                }
                            }
                        } ?>
                    </div>

                </div>
                <div class="product-img-box">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>
                    <?php echo $this->getChildHtml('media') ?>
                </div>
                <div class="product-name">
                    <span
                        class="h1"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                </div>
                <div class="main1">
                    <div class="col1">
                        <div class="product-shop">
                            <?php echo $this->getChildHtml('product_type_data') ?>
                            <?php echo $this->getChildHtml('extrahint') ?>

                            <div class="price-info">
                                <?php echo $this->getPriceHtml($_product); ?>
                                <?php echo $this->getChildHtml('bundle_prices') ?>
                                <?php echo $this->getTierPriceHtml() ?>
                            </div>


                            <?php echo $this->getChildHtml('alert_urls') ?>

                            <?php if ($_product->getShortDescription()): ?>
                                <div class="short-description">
                                    <div
                                        class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                                </div>
                            <?php endif; ?>

                            <?php echo $this->getChildHtml('other'); ?>

                        </div>

                        <div class="add-to-cart-wrapper">
                            <?php if (!$this->hasOptions()): ?>
                                <div class="add-to-box">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php echo $this->getChildHtml('addtocart') ?>
                                        <?php if ($this->helper('wishlist')->isAllow() || $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                            <span class="or"><?php echo $this->__('OR') ?></span>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php echo $this->getChildHtml('addto') ?>
                                    <?php echo $this->getChildHtml('sharing') ?>
                                </div>
                                <?php echo $this->getChildHtml('extra_buttons') ?>
                            <?php elseif (!$_product->isSaleable()): ?>

                                <div class="add-to-box">
                                    <a class="addto_disable" href="#">ADD TO CART</a>
                                    <?php echo $this->getChildHtml('addto') ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="extra-info" style="margin-bottom: 20px">
                            <?php echo $this->getReviewsSummaryHtml($_product, 'default', false) ?>
                            <?php echo $this->getChildHtml('product_type_availability'); ?>
                        </div>


                        <div class="clearer"></div>
                        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                        <?php endif; ?>
                        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        <?php endif; ?>

                    </div>

                </div>

                <div class="product-collateral toggle-content tabs">
                    <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')): ?>
                        <dl id="collateral-tabs" class="collateral-tabs">
                            <?php foreach ($detailedInfoGroup as $alias => $html): ?>
                                <?php $tabTitle = $this->escapeHtml($this->getChildData($alias, 'title')); ?>
                                <?php //$reviewsCount = Mage::app()->getLayout()->createBlock('review/product_view')->getReviewsCollection()->getSize();
                                    $sellers = Mage::getModel('marketplace/feedback')->getCollection()
                                        ->addFieldToFilter('product_id', $_product['entity_id']);
                                ?>
                                <dt class="tab">
                                    <span><?php echo strtolower($tabTitle) == 'reviews'
                                    ? $this->__('Reviews %s', '(' . count($sellers) . ')') : $tabTitle; ?></span>
                                </dt>
                                <dd class="tab-container">
                                    <div class="tab-content"><?php echo $html ?></div>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                </div>
                <div class="share-list clearfix">
                    <a id="share-buttons"></a>
                    <label>
                        Share This Page

                    </label>

                    <ul class="social clearfix addthis_toolbox">
                        <?php echo $this->getChildHtml('sharing') ?>

                    </ul>


                </div>
                <div class="proddetail-retailers clearfix">
                    <?php echo $this->getChildHtml('related_products') ?>
                </div>
                <?php echo $this->getChildHtml('upsell_products') ?>

            </form>
            <?php echo $this->getChildHtml('product_additional_data') ?>

            <!-- ---->
        </div>

        <div class="wrap-bottom">
            <div
                style="width:99%;float:left;padding:1%;font-size:0.8em; border-top: 1px solid #CCC; margin-left: -27px">

                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('men-women-top-categories')->toHtml(); ?>

                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-brands-and-new-shops')->toHtml(); ?>

                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sell-with-us-online')->toHtml(); ?>

                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('payment-methods')->toHtml(); ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function (button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                    form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function (button, url) {
            if (this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
        //]]>

    </script>






