<?php
$partner=$this->getProfileDetail();
$logo=$partner->getlogopic()==''?"noimage.png":$partner->getlogopic();
$helper=Mage::helper('marketplace');
$logo=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'avatar/'.$logo;
?>

<?php echo $this->getChildHtml();?>	
<div class="wk_profile_links" style="width:100%;">
	<a class="btn_primary" id="cprofile" href="<?php echo $this->getUrl('marketplace/seller/profile').$partner['profileurl']; ?>"><?php echo $helper->__('View Seller Profile') ?></a>
</div>